### PR TITLE
ClassDumper to catch ClassFormatException

### LINKED ISSUE #1142: Linkage Checker: ClassFormatException: Invalid byte tag in constant pool: 60
https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/536 recurred.

```
suztomo@suxtomo24:~/beam6$ ./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-extensions-sql-zetasql :checkJavaLinkage 
Configuration on demand is an incubating feature.

> Task :runners:apex:buildDependencyTree
See the report at: file:///usr/local/google/home/suztomo/beam6/runners/apex/build/classes/java/main/org/apache/beam/runners/apex/dependency-tree

> Task :checkJavaLinkage

(Wait ~10 minutes)

Exception in thread "main" org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 60
        at org.apache.bcel.classfile.Constant.readConstant(Constant.java:166)
        at org.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:63)
        at org.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:238)
        at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:143)
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:116)
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:75)
        at org.apache.bcel.util.ClassPathRepository.loadClass(ClassPathRepository.java:31)
        at com.google.cloud.tools.opensource.classpath.FixedSizeClassPathRepository.loadClass(FixedSizeClassPathRepository.java:108)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.listClasses(ClassDumper.java:399)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.findSymbolReferences(ClassDumper.java:156)
        at com.google.cloud.tools.opensource.classpath.LinkageChecker.create(LinkageChecker.java:78)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:71)

> Task :checkJavaLinkage FAILED
```

As per Elliotte's comment, it's caused by 

```
java.io.IOException: Possible corrupt jar file /Users/elharo/.m2/repository/com/ibm/icu/icu4j/2.6.1/icu4j-2.6.1.jar; could not load com.ibm.icu.impl.data.LocaleElements_zh__PINYIN; Invalid byte tag in constant pool: 60
```

Linkage Checker should handle such errors correctly.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1142 .

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 1]
```diff
@@ -398,8 +398,8 @@ Path findClassLocation(String className) {
       try {
         JavaClass javaClass = classRepository.loadClass(classFileName);
         javaClasses.add(javaClass);
-      } catch (ClassNotFoundException ex) {
-        // We couldn't find the class in the jar file where we found it.
+      } catch (ClassNotFoundException | ClassFormatException ex) {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Is a ClassNotFoundException usually caused by a corrupted jar file? Or is that just a normal version conflict where the version of the jar we have is not the one that was expected?

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: ClassNotFoundException was also caused by a corrupted JAR file as in
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1090/files

Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Yes, I'm just wondering if there are causes that are not corrupt jar files, and whether we're properly reporting them if so? It's weird that #1090 used ClassNotFoundException instead of ClassFormatException. How certain is it that that that was the right fix?

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: In the kinesis-client problem (#1090), JAR index contained a file starting with ".", which was weird. BCEL threw ClassNotFoundException because it cannot find such file in the JAR. So the fix was to catch ClassNotFoundException. I see the fix was reasonable.

Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Was it really a corrupt jar file or was BCEL buggy here?

I don't think all ClassNotFoundExceptions indicate corrupt jar files, even if that particular one does.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: As discussed, javap also show "class not found" for the kinesis JAR.

```
suztomo@suxtomo24:~$ javap -cp /usr/local/google/home/suztomo/.m2/repository/com/amazonaws/amazon-kinesis-client/1.13.0/amazon-kinesis-client-1.13.0.jar '.unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp/amazonaws/services/kinesis/multilang/messages/CheckpointMessage'
Error: class not found: .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp/amazonaws/services/kinesis/multilang/messages/CheckpointMessage

```
