### PR TITLE
Show path to the problematic artifact when the enforcer rule cannot resolve dependency

### LINKED ISSUE #795: Enforcer rule to show dependency path from root to problematic artifact
While investigating #792 , it was not straightforward to get the dependency path from `jib-maven-plugin` project to `xerces:xerces-impl:2.6.2`. It would be nice if the plugin can output such dependency path.

The dependency path in #792 :

```
xerces:xerces-impl:jar:2.6.2 (compile?)  # This is the problematic artifact
ant:ant:jar:1.6.2 (compile?)
cglib:cglib:jar:3.1 (provided?)
org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.6 (provided?)
org.apache.maven.resolver:maven-resolver-impl:jar:1.1.0 (compile)
org.apache.maven:maven-resolver-provider:jar:3.5.2 (compile)
org.apache.maven:maven-core:jar:3.5.2 (compile)   # This is direct dependency of the project
```

DependencyResolutionException has dependency tree it tries to resolve:

image

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #795 . Now it outputs the path to problematic node.

image

Now it's clear why we have `xerces:xerces-impl` in dependency tree of maven-core.

### CODE REVIEW

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 1]
```diff
@@ -270,4 +275,51 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
     }
   }
+
+  /**
+   * Returns {code Optional} describing the path from project root to a problematic artifact that
+   * caused {@link ArtifactTransferException}. An empty {@code Optional} if {@code exception} is not
+   * caused by {@link ArtifactTransferException}.
+   */
+  @VisibleForTesting
+  static Optional<String> formatDependencyPathInException(DependencyResolutionException exception) {
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: No need for Optional. We should only call this method in the case where thios is the type of the exception

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 2]
```diff
@@ -270,4 +275,51 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
+  }
+
+  private static String findPaths(DependencyNode root, Artifact artifact) {
+    ImmutableList.Builder<ImmutableList<DependencyNode>> result = ImmutableList.builder();
+
+    Deque<DependencyNode> stack = new ArrayDeque<>();
+    stack.addLast(root);
+    findArtifact(result, root, stack, artifact);
+
+    return result.build().stream()
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: This feels excessively complex. I'm surprised you needed both Joiners and Collectors.joining. Possibly you do, but too much code is included in a single statement to make that apparent.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 3]
```diff
@@ -247,7 +250,24 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
-
+      Throwable cause = e.getCause();
+      while (cause != null) {
+        if (cause instanceof ArtifactTransferException) {
+          ArtifactTransferException artifactException = (ArtifactTransferException) cause;
+          Artifact artifact = artifactException.getArtifact();
+          DependencyNode dependencyGraph = e.getResult().getDependencyGraph();
+          String pathsToArtifact = findPaths(dependencyGraph, artifact);
+          Log logger = helper.getLog();
+          logger.error("Could not get artifact " + artifact);
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: get --> "find"

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 4]
```diff
@@ -247,7 +250,24 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
+          logger.error(
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Not sure we need this line. The previous and the next seem to say it all.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 5]
```diff
@@ -247,7 +250,24 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
       throw new EnforcerRuleException("Unable to lookup a component " + e.getMessage(), e);
     } catch (DependencyResolutionException e) {
-
+      Throwable cause = e.getCause();
+      while (cause != null) {
+        if (cause instanceof ArtifactTransferException) {
+          ArtifactTransferException artifactException = (ArtifactTransferException) cause;
+          Artifact artifact = artifactException.getArtifact();
+          DependencyNode dependencyGraph = e.getResult().getDependencyGraph();
+          String pathsToArtifact = findPaths(dependencyGraph, artifact);
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: would this work more naturally as an instance method on DependencyGraph?

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 6]
```diff
@@ -247,7 +250,24 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
+          Log logger = helper.getLog();
+          logger.error("Could not get artifact " + artifact);
+          logger.error(
+              "Check dependencies of "
+                  + findDependent(dependencyGraph, Artifacts.toCoordinates(artifact)));
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: would this work more naturally as an instance method on DependencyGraph?

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 5 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: This is not our class. Renamed the variable for clarity.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 6 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Removed this line.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 4 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Removed.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 3 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Updated.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 7]
```diff
@@ -247,7 +250,21 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
     } catch (ComponentLookupException e) {
       throw new EnforcerRuleException("Unable to lookup a component " + e.getMessage(), e);
     } catch (DependencyResolutionException e) {
-
+      Throwable cause = e.getCause();
+      while (cause != null) {
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: This would be slightly more clear as a for loop:

```
for (Throwable cause = e.getCause(); cause != null; cause = cause.getCause())
```

This lets you drop the else clause

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 8]
```diff
@@ -247,7 +250,21 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
+        if (cause instanceof ArtifactTransferException) {
+          ArtifactTransferException artifactException = (ArtifactTransferException) cause;
+          Artifact artifact = artifactException.getArtifact();
+          DependencyNode dependencyRoot = e.getResult().getDependencyGraph();
+          String pathsToArtifact = findPaths(dependencyRoot, artifact);
+          Log logger = helper.getLog();
+          logger.error("Could not find artifact " + artifact);
+          logger.error("Path to the missing artifact: " + pathsToArtifact);
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Path or Paths?

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 9]
```diff
@@ -270,4 +287,32 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
       throw new EnforcerRuleException("Failed to collect dependency " + ex.getMessage(), ex);
     }
   }
+
+  private static String findPaths(DependencyNode root, Artifact artifact) {
+    ImmutableList.Builder<ImmutableList<DependencyNode>> result = ImmutableList.builder();
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: This would be clearer if you added an overloaded findArtifact(root, artifact) method that didn't take the intermediate state arguments and returned the list.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 10]
```diff
@@ -270,4 +287,32 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
+    // Joining one or more paths to the artifact
+    return Joiner.on("\n").join(paths);
+  }
+
+  private static void findArtifact(
+      ImmutableList.Builder<ImmutableList<DependencyNode>> result,
+      DependencyNode node,
+      Deque<DependencyNode> path,
+      Artifact artifact) {
+    if (Artifacts.toCoordinates(node.getArtifact()).equals(Artifacts.toCoordinates(artifact))) {
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Any chance node.getArtifact returns null here? I ask because we're specifically dealing with missing artifacts.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 9 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Added `ImmutableList<ImmutableList<DependencyNode>> findArtifactPaths(DependencyNode node, Artifact artifact)`

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 10 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: No, `node.getArtifact()` does not return null. `node.getArtifact().getFile()` may return null if artifact is missing.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 3 above)
Comment (elharo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: I think you need to push your changes.

Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Pushed.
