### PR TITLE
More system properties for Netty

### LINKED ISSUE #348: Maven variables in dependency
`io.netty:netty-all:jar:4.1.31.Final` depends on `io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.31.Final`. But the tool does not interpret the variables when fetching dependencies and thus causes error.

```
WARNING: Could not resolve io.netty:netty-all:jar:4.1.31.Final (compile?) under [org.springframework.cloud:spring-cloud-zookeeper-config:jar:2.1.0.RC2 (compile), org.springframework.boot:spring-boot-starter-web:jar:2.1.1.RELEASE (compile?), org.springframework:spring-web:jar:5.1.3.RELEASE (compile), io.netty:netty-all:jar:4.1.31.Final (compile?)] Exception: Could not find artifact io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.31.Final in central (http://repo1.maven.org/maven2/)

org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.31.Final in central (http://repo1.maven.org/maven2/)

	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:355)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.resolveCompileTimeDependencies(DependencyGraphBuilder.java:129)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.resolveCompileTimeDependencies(DependencyGraphBuilder.java:84)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.levelOrder(DependencyGraphBuilder.java:282)
	at com.google.cloud.tools.opensource.dependencies.DependencyGraphBuilder.getStaticLinkageCheckDependencyGraph(DependencyGraphBuilder.java:164)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToDependencyPaths(ClassPathBuilder.java:86)
	at com.google.cloud.tools.opensource.classpath.ClassPathBuilder.artifactsToClasspath(ClassPathBuilder.java:56)
	at com.google.cloud.tools.opensource.classpath.StaticLinkageCheckOptionTest.testConfigureMavenRepositories(StaticLinkageCheckOptionTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.31.Final in central (http://repo1.maven.org/maven2/)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:338)
	... 29 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.netty:netty-transport-native-epoll:jar:${os.detected.name}-${os.detected.arch}:4.1.31.Final in central (http://repo1.maven.org/maven2/)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:368)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

Code to reproduce the error

```
    Artifact nettyArtifact =
        new DefaultArtifact("io.netty:netty-all:4.1.31.Final");

    List<Path> paths =
        ClassPathBuilder.artifactsToClasspath(ImmutableList.of(nettyArtifact));
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #348.

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 1]
```diff
@@ -52,25 +52,50 @@
...
+    if (ImmutableList.of("x8664", "amd64", "ia32e", "em64t", "x64").contains(osArchNormalized)) {
+      osDetectedArchValue = "x86_64";
+    } else {
+      osDetectedArchValue = "x86_32";
+    }
+    System.setProperty(osDetectedArchKey, osDetectedArchValue);
+
+    String osDetectedClassifierKey = "os.detected.classifier";
+    System.setProperty(
+        osDetectedClassifierKey, String.format("%s-%s", osDetectedNameValue, osDetectedArchValue));
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: > Property: os.detected.classifier
> You can also use the ${os.detected.classifier} property, which is a shortcut of ${os.detected.name}-${os.detected.arch}.
https://github.com/trustin/os-maven-plugin#property-osdetectedclassifier

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 2]
```diff
@@ -52,25 +52,46 @@
...
   }
 
   // caching cuts time by about a factor of 4.
   private static final Map<String, DependencyNode> cacheWithProvidedScope = new HashMap<>();
   private static final Map<String, DependencyNode> cacheWithoutProvidedScope = new HashMap<>();
 
+  private static void setDetectedOsSystemProperties() {
+    // System properties to select Netty dependencies through os-maven-plugin
+    // Definition of the properties: https://github.com/trustin/os-maven-plugin
+    String nonAlphaNumericPattern = "[^a-z0-9]+";
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Make this a constant? And maybe use `Pattern.compile()`?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 3]
```diff
@@ -52,25 +52,46 @@
...
+    String osNameNormalized =
+        System.getProperty("os.name", "generic")
+            .toLowerCase(Locale.ENGLISH)
+            .replaceAll(nonAlphaNumericPattern, "");
+
+    String osDetectedNameValue;
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: It's easier to read code that doesn't multiply-assign. What if you extracted a method that returned the os.detected.name value, and this method simply did `System.setProperty("os.detected.name", osDetectedName());`

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 4]
```diff
@@ -52,25 +52,46 @@
...
+    } else {
+      // Since we only load the dependency graph, not actually use the
+      // dependency, it doesn't matter a great deal which one we pick.
+      osDetectedNameValue = "linux";
+    }
+    System.setProperty("os.detected.name", osDetectedNameValue);
+
+    String osDetectedArchValue;
+    String osArchNormalized = System.getProperty("os.arch").replaceAll(nonAlphaNumericPattern, "");
+    if (ImmutableList.of("x8664", "amd64", "ia32e", "em64t", "x64").contains(osArchNormalized)) {
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: This could be a constant `ImmutableList`, or you could switch on the string.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Made it to a switch statement.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 3 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Updated the logic with `osDetectedName()` and `osDetectedArch()`

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 2 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Now it's constant `private static final Pattern NON_ALPHA_NUMERIC_PATTERN = Pattern.compile("[^a-z0-9]+")`.

**Comment by suztomo** [comment]
@netdpb Applied code review. PTAL.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 5]
```diff
@@ -50,7 +51,9 @@
   private static final Logger logger = Logger.getLogger(DependencyGraphBuilder.class.getName());
   
   private static final RepositorySystem system = RepositoryUtility.newRepositorySystem();
-  
+
+  private static final Pattern NON_ALPHA_NUMERIC_PATTERN = Pattern.compile("[^a-z0-9]+");
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Tiny nit: You don't need to have "_PATTERN" since we know the type.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 6]
```diff
@@ -62,34 +65,45 @@
   private static void setDetectedOsSystemProperties() {
     // System properties to select Netty dependencies through os-maven-plugin
     // Definition of the properties: https://github.com/trustin/os-maven-plugin
-    String nonAlphaNumericPattern = "[^a-z0-9]+";
+
+    System.setProperty("os.detected.name", osDetectedName());
+
+    System.setProperty("os.detected.arch", osDetectedArch());
+
+    System.setProperty("os.detected.classifier", osDetectedName() + "-" + osDetectedArch());
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Instead of recalculating these two, maybe just use System.getProperty()?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 7]
```diff
@@ -62,34 +65,45 @@
   private static void setDetectedOsSystemProperties() {
     // System properties to select Netty dependencies through os-maven-plugin
     // Definition of the properties: https://github.com/trustin/os-maven-plugin
-    String nonAlphaNumericPattern = "[^a-z0-9]+";
+
+    System.setProperty("os.detected.name", osDetectedName());
+
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Do we need this blank line here anymore? Or the next one?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 8]
```diff
@@ -62,34 +65,45 @@
...
+    System.setProperty("os.detected.classifier", osDetectedName() + "-" + osDetectedArch());
+  }
+
+  private static String osDetectedName() {
     String osNameNormalized =
-        System.getProperty("os.name", "generic")
-            .toLowerCase(Locale.ENGLISH)
-            .replaceAll(nonAlphaNumericPattern, "");
+        NON_ALPHA_NUMERIC_PATTERN
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: I forgot about `CharMatcher` in Guava! Consider this:

```java
private static final CharMatcher ALPHA_NUMERIC = CharMatcher.inRange('a', 'z').or(CharMatcher.inRange('0', '9'));

String osNameNormalized =
    ALPHA_NUMERIC.retainFrom(System.getProperty("os.name", "generic").toLowerCase(ENGLISH));
```

A little simpler to do `retainFrom(foo)` than `matcher(foo).replaceAll("")`.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: `retainFrom` is nice. Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 5 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Removed _PATTERN

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 7 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Removed them.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 6 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Introduced variables for them.
