### PR TITLE
Linkage Checker enforcer rule to resolve os.detected.classifier

### LINKED ISSUE #809: Enforcer rule for spring-cloud-gcp 1.1.2-RELEASE fails with missing dependency
While waiting for #769, I tried an old version of spring-cloud-gcp that does not depends on spring-core 5.2.0.M3. It fails as below:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-linkage-checker) @ spring-cloud-gcp-core ---
[WARNING] The POM for org.apache.logging.log4j:log4j-api-java9:zip:2.11.2 is missing, no dependency information available
[WARNING] The POM for org.apache.logging.log4j:log4j-core-java9:zip:2.11.2 is missing, no dependency information available
[WARNING] The POM for xerces:xerces-impl:jar:2.6.2 is missing, no dependency information available
[WARNING] The POM for org.jruby.joni:joni:jar:2.1.1-SNAPSHOT is missing, no dependency information available
[ERROR] Could not find artifact org.apache.logging.log4j:log4j-api-java9:zip:2.11.2
[ERROR] Paths to the missing artifact:
 org.springframework.cloud:spring-cloud-gcp-core:jar:1.1.2.RELEASE
 > org.springframework:spring-core:jar:5.1.8.RELEASE (compile)
 > org.springframework:spring-jcl:jar:5.1.8.RELEASE (compile)
 > org.apache.logging.log4j:log4j-api:jar:2.11.2 (compile?)
 > org.apache.logging.log4j:log4j-api-java9:zip:2.11.2 (provided?)
```

Investigating the error.

After zip filtering (#811), it still has error for Netty:

```
[ERROR] Could not find artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.25.Final
[ERROR] Paths to the missing artifact:
 org.springframework.cloud:spring-cloud-gcp-core:jar:1.1.2.RELEASE
 > org.springframework:spring-core:jar:5.1.8.RELEASE (compile)
 > io.projectreactor:reactor-core:jar:3.2.10.RELEASE (compile?)
 > io.micrometer:micrometer-core:jar:1.1.5 (compile?)
 > io.projectreactor.netty:reactor-netty:jar:0.8.9.RELEASE (compile?)
 > io.netty:netty-handler:jar:4.1.36.Final (compile?)
 > io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.25.Final (compile?
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #809 . 

This PR uses RepositorySystemSession that contains the properties when resolving project's dependency tree.

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 1]
```diff
@@ -57,22 +58,25 @@
...
-    setDetectedOsSystemProperties();
+    detectOsProperties().forEach(System::setProperty);
   }
 
   // caching cuts time by about a factor of 4.
   private static final Map<String, DependencyNode> cacheWithProvidedScope = new HashMap<>();
   private static final Map<String, DependencyNode> cacheWithoutProvidedScope = new HashMap<>();
 
-  private static void setDetectedOsSystemProperties() {
+  public static ImmutableMap<String, String> detectOsProperties() {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: reusing existing logic.

I tried calling `setDetectedOsSystemProperties` at the beginning of `LinkageCheckerRule.execute`. But it was too late to inject the properties into the RepositorySystemSession.
