### PR TITLE
Linkage Checker to report missing parent class or interface

### LINKED ISSUE #933: Linkage Checker reports wrong class when superclass/interface is missing
Linkage Checker reports wrong class when superclass/interface is missing. 

While investigating #929 , I found that some of the missing classes are indeed in the class path but their interfaces are missing.

Example is `com.oracle.graal.pointsto.meta.AnalysisType` class reported as missing. However it is its interface `jdk.vm.ci.meta.ResolvedJavaType` that is not available in the class path. 

image

Memo

`getClassHierarchy` does not throw ClassNotFoundException even for `org.graalvm.compiler.graph.NodeSourcePosition` whose parent class is missing, because it returns Iterable.

`targetJavaClass.getAllInterfaces` throws ClassNotFoundException for missing `jdk.vm.ci.code.BytecodePosition` because `getAllInterfaces` reads all superclasses to find interfaces.

```
      Iterable<JavaClass> typesToCheck =
          Iterables.concat(
              getClassHierarchy(targetJavaClass),
              Arrays.asList(targetJavaClass.getAllInterfaces()));
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #933

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java [hunk 1]
```diff
@@ -202,6 +203,12 @@ private LinkageChecker(
             new SymbolProblem(symbol, ErrorType.INCOMPATIBLE_CLASS_CHANGE, containingClassFile));
       }
 
+      // Check the existence of the parent class or interface for the class
+      Optional<SymbolProblem> parentSymbolProblem = findParentSymbolProblem(targetClassName);
+      if (parentSymbolProblem.isPresent()) {
+        return parentSymbolProblem;
+      }
+
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: The problem was that, if any of superclasses or interfaces was missing, the subsequent operations to check method existence in them would fail. Screenshot of the stacktrace in #933

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java [hunk 2]
```diff
@@ -405,4 +412,41 @@ private boolean isClassAccessibleFrom(JavaClass javaClass, String sourceClassNam
...
+   */
+  private Optional<SymbolProblem> findParentSymbolProblem(String baseClassName) {
+    Queue<String> queue = new ArrayDeque<>();
+    queue.add(baseClassName);
+    while (!queue.isEmpty()) {
+      String className = queue.remove();
+      if (Object.class.getName().equals(className)) {
+        continue; // java.lang.Object is the root of the inheritance tree
+      }
+      JavaClass baseClass;
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: This could be pushed into the try block

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java [hunk 3]
```diff
@@ -405,4 +412,41 @@ private boolean isClassAccessibleFrom(JavaClass javaClass, String sourceClassNam
...
+        baseClass = classDumper.loadJavaClass(className);
+        queue.add(baseClass.getSuperclassName());
+      } catch (ClassNotFoundException ex) {
+        // baseClass is not updated yet
+        SymbolProblem problem =
+            new SymbolProblem(new ClassSymbol(className), ErrorType.SYMBOL_NOT_FOUND, null);
+        return Optional.of(problem);
+      }
+
+      for (String interfaceName : baseClass.getInterfaceNames()) {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: This and the following should also be pushed into the try block.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java [hunk 4]
```diff
@@ -856,4 +857,50 @@ public void testFindSymbolProblems_shouldNotDetectWhitelistedClass()
...
+            new DefaultArtifact("com.oracle.substratevm:svm:19.2.0.1"));
+    ImmutableList<Path> jars =
+        dependencies.list().stream()
+            .map(path -> path.getLeaf().getFile().toPath())
+            .collect(toImmutableList());
+
+    LinkageChecker linkageChecker = LinkageChecker.create(jars, jars);
+    ImmutableSet<SymbolProblem> problems = linkageChecker.findSymbolProblems().keySet();
+    assertFalse(
+        "Graal's AnalysisType, whose interface is missing, should not be reported",
```
Comment (elharo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java]: GraalVM's

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java [hunk 5]
```diff
@@ -856,4 +857,50 @@ public void testFindSymbolProblems_shouldNotDetectWhitelistedClass()
...
+        problems.stream()
+            .anyMatch(
+                problem ->
+                    problem
+                        .getSymbol()
+                        .getClassName()
+                        .equals("com.oracle.graal.pointsto.meta.AnalysisType")));
+    assertFalse(
+        "Graal's NodeSourcePosition, whose superclass is missing, should not be reported",
```
Comment (elharo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java]: GraalVM's

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java (hunk 4 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java]: Fixed

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java (hunk 5 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java]: Fixed

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java (hunk 2 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: No, I tried that but this declaration cannot be in the try block. because baseClass is used after try block at Line 439.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java (hunk 3 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: No, I tried that but it would not work because interfaceName is used in the catch clause.

Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: I meant this should be pu8shed into the try block above, not below. You can nest the try blocks.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: I was able to remove second try block by introducing `potentiallyMissingTypeName` variable ([link](https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/935/files#diff-e275d9cce5c577df64bfd6fe55a5cdfaR434)). Does that look good?
