### PR TITLE
Enforcer rule not to show empty path when path cannot be found

### LINKED ISSUE #834: Enforcer rule: Paths to the missing artifact: (empty)
The following output is from Ray's [grpc-java-by-example/chat-example/chat-vaadin-client](https://github.com/saturnism/grpc-java-by-example/tree/master/chat-example/chat-vaadin-client). Investigate why the message does not have path.

```
[ERROR] Could not find artifact org.jboss.logging:jboss-logging:pom:3.0.0.Beta5-SNAPSHOT
[ERROR] Paths to the missing artifact: 
[WARNING] Rule 0: com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule warned with message:
Unable to build a dependency graph: Could not resolve dependencies for project org.test:chat-vaadin-client:war:1.0-SNAPSHOT: Failed to collect dependencies at
 com.vaadin:vaadin-server:jar:8.1.6
 -> com.vaadin:vaadin-push:jar:8.1.6
 -> com.vaadin.external.atmosphere:atmosphere-runtime:jar:2.4.11.vaadin2
 -> org.atmosphere.jboss.as:jboss-as-websockets:jar:0.5
 -> org.jboss.as:jboss-as-server:jar:7.1.1.Final
 -> org.jboss.as:jboss-as-controller:jar:7.1.1.Final
 -> org.jboss.msc:jboss-msc:jar:1.0.2.GA
 -> org.jboss.logging:jboss-logging-processor:jar:1.0.0.Beta5
 -> org.jboss.logging:jboss-logging:jar:3.0.0.Beta5-SNAPSHOT
```

Among the lines, the bug is the following line:

```
[ERROR] Paths to the missing artifact: 
```

The dependency graph has been modified when it is passed to ArtifactTransferException. The graph only has org.jboss.logging:jboss-logging-processor:jar:**1.0.0.Final**.

```
[ERROR] Path to jboss logging:org.test:chat-vaadin-client:war:1.0-SNAPSHOT > com.vaadin:vaadin-push:jar:8.1.6 (compile) > com.vaadin.external.atmosphere:atmosphere-runtime:jar:2.4.11.vaadin2 (compile) > org.atmosphere.jboss.as:jboss-as-websockets:jar:0.5 (provided) > org.jboss.as:jboss-as-server:jar:7.1.1.Final (provided) > org.jboss.logging:jboss-logging-processor:jar:1.0.0.Final (provided)
```

But in that case shouldn't `projectDependenciesResolver.resolve` fail?

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #834 .

When the rule cannot find the empty path, it should say so, rather than outputting an empty string.

# Enhancement

When enforcer rule is applied to Ray's grpc-java-by-example/chat-example/chat-vaadin-client, it no longer show `[ERROR] Paths to the missing artifact: ` with an empty string as the path:

```
[ERROR] Could not find artifact org.jboss.logging:jboss-logging:pom:3.0.0.Beta5-SNAPSHOT
[WARNING] The transformed dependency graph does not contain the missing artifact
[WARNING] Rule 0: com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule warned with message:
Unable to build a dependency graph: Could not resolve dependencies for project org.test:chat-vaadin-client:war:1.0-SNAPSHOT: Failed to collect dependencies at com.vaadin:vaadin-server:jar:8.1.6 -> com.vaadin:vaadin-push:jar:8.1.6 -> com.vaadin.external.atmosphere:atmosphere-runtime:jar:2.4.11.vaadin2 -> org.atmosphere.jboss.as:jboss-as-websockets:jar:0.5 -> org.jboss.as:jboss-as-server:jar:7.1.1.Final -> org.jboss.as:jboss-as-controller:jar:7.1.1.Final -> org.jboss.msc:jboss-msc:jar:1.0.2.GA -> org.jboss.logging:jboss-logging-processor:jar:1.0.0.Beta5 -> org.jboss.logging:jboss-logging:jar:3.0.0.Beta5-SNAPSHOT

```

# Why a path to the problematic artifact cannot be found?

it's because the graph is transformed (dependency mediation) before throwing the exception. In Maven's dependency collection, the following steps happen:

1. collect dependency graph. Record exception if any rather than aborting here.
2. transform graph (dependency mediation)
3. throw exception if 1st step got an exception.
4. return the graph

When there is a problem in step#1, then the exception is thrown at step#3. At this point, the graph is transformed and thus the graph may not have the cause of the artifact of the exception.

[MNG-6732](https://issues.apache.org/jira/browse/MNG-6732) DefaultArtifactDescriptorReader.loadPom to check IGNORE_MISSING policy upon ArtifactTransferException is an enhancement to avoid such situation (not reviewed).

### CODE REVIEW

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 1]
```diff
@@ -271,7 +271,14 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
             Iterables.getFirst(findArtifactPaths(root, artifact), ImmutableList.of());
         if (DependencyGraphBuilder.requiredDependency(firstArtifactPath)) {
           logger.error("Could not find artifact " + artifact);
-          logger.error("Paths to the missing artifact: " + pathsToArtifact);
+          if (pathsToArtifact.isEmpty()) {
+            // Maven may throw ArtifactDescriptorException even when the artifact is not needed
+            // in the final dependency graph after transformation (MNG-6732)
+            logger.warn(
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: why warning instead of error?

Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: It’s warning because the fact “not finding node in graph” is not the cause of the failure.

Comment (elharo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: In that case, why log and throw at all?

Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: > why log

Because I want explanation why the path is empty. (This path emptiness is not the cause of the failure)

> why throw at all

Because `resolutionException` is the cause of the failure.

Comment (elharo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: I'm still not following why it's a warning here, but an error previous to this change and in the else statement below.

Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Updated to error().

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 2]
```diff
@@ -271,7 +271,14 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
             Iterables.getFirst(findArtifactPaths(root, artifact), ImmutableList.of());
         if (DependencyGraphBuilder.requiredDependency(firstArtifactPath)) {
           logger.error("Could not find artifact " + artifact);
-          logger.error("Paths to the missing artifact: " + pathsToArtifact);
+          if (pathsToArtifact.isEmpty()) {
+            // Maven may throw ArtifactDescriptorException even when the artifact is not needed
+            // in the final dependency graph after transformation (MNG-6732)
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: URL to the bug would be helpful

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 3]
```diff
@@ -271,7 +271,14 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
             Iterables.getFirst(findArtifactPaths(root, artifact), ImmutableList.of());
         if (DependencyGraphBuilder.requiredDependency(firstArtifactPath)) {
           logger.error("Could not find artifact " + artifact);
-          logger.error("Paths to the missing artifact: " + pathsToArtifact);
+          if (pathsToArtifact.isEmpty()) {
+            // Maven may throw ArtifactDescriptorException even when the artifact is not needed
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: may throw or does throw?

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 2 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Added URL.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 3 above)
Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Updated to "On certain conditions, Maven throws ..." to clarify "may".
