### PR TITLE
Convert lambda to for loop so breakpoints can be set and single stepped

### LINKED ISSUE #524: Enforcer rule fails with NullPointerException for a new project
For a user's Maven project that uses linakge-checker-enforcer-rules (default `dependencyManagement:DEPENDENCIES`), the rule's behavior differs depending on locally-installed artifact of the project.

- When a project has already run "mvn clean", LinkageCheckerEnforcerRule checks the class path containing the jar file.

- When a project has not yet run "mvn clean", the rule cannot check the class files in the project.

This is unexpected behavior. Because "mvn validate" lifecycle is before compile, the rule should not touch class files in the project.

Also, the enforcer rule fails with NullPointerException for a new project that has not yet run "mvn install".

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce) on project no-such-method-error-example: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce (enforce) on project no-such-method-error-example: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:993)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:345)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M2:enforce failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:145)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:993)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:345)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.NullPointerException
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:175)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.Iterator.forEachRemaining (Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:499)
    at com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule.findProjectClasspath (LinkageCheckerRule.java:195)
    at com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule.execute (LinkageCheckerRule.java:116)
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:194)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:993)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:345)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:191)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 

```

### PR DESCRIPTION
**Pull request by elharo**
@netdpb also catches a NullPointerException should one arise again. It's still possible to get one if the user binds this to the wrong phase. It's also worth noting that when the NullPointerException arose the lambda obscured the source of the problem. 

fix #524

### CODE REVIEW

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 1]
```diff
@@ -186,13 +184,26 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
+        if (artifact != null) { // why is this possible?
+          File file = artifact.getFile();
+          // and this very first one does not have a file; i.e. file == null
+          // but why do we care? perhaps we're assuming there is a jar file in
+          // the classpath but what we really need for this one is a classes directory
+          Path path = file.toPath();
+          builder.add(path);
+        }
+      }
+      ImmutableList<Path> built = builder.build();
```
Comment (netdpb) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]:
```suggestion
      return builder.build();
```

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 2]
```diff
@@ -186,13 +184,26 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
+      return built;
+    } catch (NullPointerException e) {
```
Comment (netdpb) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Instead of catching NPE, handle nulls in the main code. In this case, `Artifact.getFile()` can return `null` (and is so documented), so why are we throwing at all?

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 3]
```diff
@@ -186,13 +184,26 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
...
 
-      return StreamSupport.stream(
-              traverser.breadthFirst(resolutionResult.getDependencyGraph()).spliterator(), false)
-          .map(DependencyNode::getArtifact)
-          .filter(Objects::nonNull)
-          .map(Artifact::getFile)
-          .map(File::toPath)
-          .collect(toImmutableList());
+      DependencyNode dependencyGraph = resolutionResult.getDependencyGraph();
+      Iterable<DependencyNode> breadthFirst = traverser.breadthFirst(dependencyGraph);
```
Comment (netdpb) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Consider inlining this; it doesn't really need to exist outside the for.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 2 above)
Comment (elharo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: good idea; done

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 3 above)
Comment (netdpb) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Sorry, I meant the `traverser.breadthFirst(...)`. But whatever.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 4]
```diff
@@ -196,14 +197,15 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
           // and this very first one does not have a file; i.e. file == null
           // but why do we care? perhaps we're assuming there is a jar file in
           // the classpath but what we really need for this one is a classes directory
+          if (file == null) {
+            throw new EnforcerRuleException(
```
Comment (netdpb) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Why is this an exception? What did the user do wrong, and what should they do differently?

**Comment by patflynn** [comment]
is there not tooling in place now to effectively debug Java 8+ style lambda code?

@etanshaul @ivanporty who may have some experience with this.

Also came across https://stackoverflow.com/questions/24541786/how-to-debug-stream-map-with-lambda-expressions

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java (hunk 4 above)
Comment (elharo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Good point. Expanded exception message to include probable cause.

**Comment by elharo** [comment]
IntelliJ may do a better job of this than Eclipse. The Stack Overflow thread consists of Eclipse users trying to figure this out. In general lambdas are antithetical the practice of single stepping through code to figure out what's going wrong since there's no determined order. In this case, the critical piece of information to understand what was happening was that the exception was only thrown for the *first* artifact in the list and not the subsequent ones. That is, order of execution does matter in this case.
