### PR TITLE
LinkageCheckerTest.testFindLinkageProblems_referenceToJava11Method fails in Java 11 to use Assume Java 8 runtime

### LINKED ISSUE #1822: LinkageCheckerTest.testFindLinkageProblems_referenceToJava11Method fails in Java 11
Towards #1821 .

```
suztomo-macbookpro44% which java
/Library/Java/JavaVirtualMachines/jdk-11-latest/Contents/Home/bin/java
suztomo-macbookpro44% pwd        
/Users/suztomo/cloud-opensource-java/dependencies
suztomo-macbookpro44% mvn test -Dtest=LinkageCheckerTest#testFindLinkageProblems_referenceToJava11Method 
...
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.154 s <<< FAILURE! - in com.google.cloud.tools.opensource.classpath.LinkageCheckerTest
[ERROR] testFindLinkageProblems_referenceToJava11Method(com.google.cloud.tools.opensource.classpath.LinkageCheckerTest)  Time elapsed: 1.081 s  <<< FAILURE!
com.google.common.truth.AssertionErrorWithFacts: 
value of           : findLinkageProblems()
expected to contain: java.nio.CharBuffer's method flip() is expected to return java.nio.CharBuffer but instead returns java.nio.Buffer referenced by ClassFile{location=com.google.protobuf:protobuf-java:3.12.4, className=com.google.protobuf.TextFormat}
but was            : []
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerTest.testFindLinkageProblems_referenceToJava11Method(LinkageCheckerTest.java:1150)

```

The problem of `java.nio.CharBuffer`'s invalid return type is only applicable to Java 8 runtime.

Should Linkage Checker have a mode to switch Java runtime version?

What's user's experience? In a certain scenario, should a user only care about Java 8? Or Just Java 11?

What about a user who currently uses Java 11 in their builds but wants to ensure their library runs well on Java 8?

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1822 . If we run the test on Java 11, the test says

```
org.junit.AssumptionViolatedException: got: "11.0.4", expected: a string starting with "1.8.0"
```

and JUnit ignores the test.

### CODE REVIEW

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java [hunk 1]
```diff
@@ -1130,6 +1132,8 @@ public void testFindLinkageProblems_grpcAndGuava() throws IOException {
   public void testFindLinkageProblems_referenceToJava11Method() throws IOException {
     // protobuf-java 3.12.4 references a Java 11 method that does not exist in Java 8
     // https://github.com/protocolbuffers/protobuf/issues/7827
+    Assume.assumeThat(System.getProperty("java.version"), startsWith("1.8.0"));
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java:1135]: Static import reads well, compared with `StringStartsWith.startsWith`.

Comment (elharo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java:1135]: why not use java.lang.String.startsWith()? In not, because that method is much more familiar, this really can't be a static import.

Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java:1135]: `String.startsWith` would give a message `got false expected true`.

This `StringStartsWith.startsWith` gives more clear message: `got: "11.0.4", expected: a string starting with "1.8.0"`.

Comment (elharo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java:1135]: Fair enough. Static import is still not a good idea here given the confusion with the better known String.startsWith method.

**Review by elharo — APPROVED** [review]
