### PR TITLE
GradleDependencyMediation to handle artifact with no file

### LINKED ISSUE #2042: GradleDependencyMediation throws NullPointerException when an artifact is not found
GradleDependencyMediation throws NullPointerException when an artifact is not found. It should handle the case where JAR file is missing.

Screen Shot 2021-04-29 at 14 35 13

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #2042

### CODE REVIEW

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java [hunk 1]
```diff
@@ -170,6 +170,22 @@ public void testResolveClassPath_invalidCoordinate() throws RepositoryException
...
         artifactProblems.get(0).toString());
+    Truth.assertThat(result.getClassPath()).isEmpty();
+  }
+
+  @Test
+  public void testResolveClassPath_invalidCoordinate_Gradle() throws RepositoryException {
+    Artifact nonExistentArtifact = new DefaultArtifact("io.grpc:nosuchartifact:1.2.3");
+    ClassPathResult result =
+        classPathBuilder.resolve(
+            ImmutableList.of(nonExistentArtifact), true, DependencyMediation.GRADLE);
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java:181]: This was throwing NullPointerException.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java [hunk 2]
```diff
@@ -159,17 +159,27 @@ public void testResolveClassPath_optionalDependency()
...
+    testResolveClassPath_invalidCoordinate(DependencyMediation.GRADLE);
+  }
+
+  private void testResolveClassPath_invalidCoordinate(DependencyMediation dependencyMediation)
+      throws RepositoryException {
     Artifact nonExistentArtifact = new DefaultArtifact("io.grpc:nosuchartifact:1.2.3");
     ClassPathResult result =
-        classPathBuilder.resolve(
-            ImmutableList.of(nonExistentArtifact), true, DependencyMediation.MAVEN);
+        classPathBuilder.resolve(ImmutableList.of(nonExistentArtifact), true, dependencyMediation);
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java:175]: This was throwing NullPointerException inside for `DependencyMediation.GRADLE`.

**Review by elharo — APPROVED** [review]
