### PR TITLE
DependencyGraphBuilder.buildLinkageCheckDependencyGraph to catch DependencyResolutionException

### LINKED ISSUE #1209: DependencyGraphBuilder.buildLinkageCheckDependencyGraph should catch DependencyResolutionException
DependencyGraphBuilder.buildLinkageCheckDependencyGraph should catch DependencyResolutionException

- `ant:ant:jar:1.6.2 (compile?)`
- `org.springframework:org.springframework.context:jar:2.5.6.SEC01 (compile)`

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1209 .

Motivation of this change is [testBuildLinkageCheckDependencyGraph_catchRootException](https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1210/files#r378501664), where DependencyGraphBuilder throws an exception for unresolved dependencies of "ant:1.6.2", rather than returning UnresolvedArtifactProblems.

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java [hunk 1]
```diff
@@ -68,15 +69,20 @@ public ClassPathResult resolve(List<Artifact> artifacts) throws RepositoryExcept
     }
     // dependencyGraph holds multiple versions for one artifact key (groupId:artifactId)
     DependencyGraphResult result =
-        dependencyGraphBuilder.getStaticLinkageCheckDependencyGraph(artifacts);
+        dependencyGraphBuilder.buildLinkageCheckDependencyGraph(artifacts);
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java]: Renamed getStaticLinkageCheckDependencyGraph to build ... to follow the previous refactoring.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java [hunk 2]
```diff
@@ -78,4 +81,44 @@ public static String formatProblems(Iterable<ArtifactProblem> problems) {
     }
     return output.toString();
   }
+
+  @Override
+  public boolean equals(Object other) {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java]: Equality function is added to dedup at https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1210/files#diff-659d7bf4148f942fcc1eb60a50a2ee80R261

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java [hunk 3]
```diff
@@ -131,15 +130,15 @@ public void testResolveClassPath_optionalDependency() throws RepositoryException
   }
 
   @Test
-  public void testResolveClassPath_invalidCoordinate() {
+  public void testResolveClassPath_invalidCoordinate() throws RepositoryException {
     Artifact nonExistentArtifact = new DefaultArtifact("io.grpc:nosuchartifact:1.2.3");
-    try {
-      classPathBuilder.resolve(ImmutableList.of(nonExistentArtifact));
-      Assert.fail("Invalid Maven coodinate should raise RepositoryException");
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilderTest.java]: With this PR, missing artifact is recorded as `getArtifactProblem()`, not as an exception.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java (hunk 2 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java]: Equality test is added in ArtifactProblemTest.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderTest.java [hunk 4]
```diff
@@ -234,14 +233,34 @@ public void testConfigureAdditionalMavenRepositories_notToUseMavenCentral()
...
+        .comparingElementsUsing(problemOnArtifact)
+        .contains("com.google.guava:guava:28.2-jre");
+  }
+
+  @Test
+  public void testBuildLinkageCheckDependencyGraph_catchRootException() throws RepositoryException {
+    // This should not throw exception
+    DependencyGraphResult result =
+        dependencyGraphBuilder.buildLinkageCheckDependencyGraph(
+            ImmutableList.of(new DefaultArtifact("ant:ant:jar:1.6.2")));
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderTest.java]: This is the motivation of this PR. Before this PR, the function threw DependencyResolutionException. Such errors should be reported as `result.getArtifactProblems()`.

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 5]
```diff
@@ -352,14 +339,4 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
       throw new EnforcerRuleException("Failed to collect dependency " + ex.getMessage(), ex);
     }
   }
-
-  private static ImmutableList<List<DependencyNode>> findArtifactPaths(
```
Comment (suztomo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: This function has moved to DependencyGraphBuilder.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1210/files#diff-659d7bf4148f942fcc1eb60a50a2ee80R283

File: dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderTest.java [hunk 6]
```diff
@@ -234,14 +233,34 @@ public void testConfigureAdditionalMavenRepositories_notToUseMavenCentral()
...
+    DependencyGraphResult result =
+        graphBuilder.buildCompleteGraph(new Dependency(artifact, "compile"));
+    Truth.assertThat(result.getArtifactProblems())
+        .comparingElementsUsing(problemOnArtifact)
+        .contains("com.google.guava:guava:28.2-jre");
+  }
+
+  @Test
+  public void testBuildLinkageCheckDependencyGraph_catchRootException() throws RepositoryException {
+    // This should not throw exception
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderTest.java]: This is the motivation of this PR. Before this PR, the function threw DependencyResolutionException. Such errors should be reported as `result.getArtifactProblems()`.

File: dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java [hunk 7]
```diff
@@ -339,23 +339,18 @@ private static ArtifactCache loadArtifactInfo(List<Artifact> artifacts) {
...
-        globalDependencies.add(completeDependencies);
-
-        // picks versions according to Maven rules
-        DependencyGraphResult transitiveDependencyResult =
-            dependencyGraphBuilder.buildGraph(new Dependency(artifact, "compile"));
-        DependencyGraph transitiveDependencies = transitiveDependencyResult.getDependencyGraph();
-
-        ArtifactInfo info = new ArtifactInfo(completeDependencies, transitiveDependencies);
-        infoMap.put(artifact, info);
-      } catch (RepositoryException ex) {
```
Comment (suztomo) [inline dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: This exception is not thrown any more.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java [hunk 8]
```diff
@@ -78,4 +81,44 @@ public static String formatProblems(Iterable<ArtifactProblem> problems) {
...
+      if (!Objects.equals(dependencyA, dependencyB)) {
+        return false;
+      }
+    }
+    return true;
+  }
+
+  @Override
+  public int hashCode() {
+    ImmutableList<Dependency> dependencyList =
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java]: DependencyNode does not have good equals/hashcode. So leveraging Dependency class.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 9]
```diff
@@ -128,21 +131,9 @@ public DependencyGraphBuilder(Iterable<String> mavenRepositoryUrls) {
     this.repositories = repositoryListBuilder.build();
   }
 
-  private DependencyNode resolveCompileTimeDependencies(DependencyNode root)
-      throws DependencyCollectionException, DependencyResolutionException {
-    return resolveCompileTimeDependencies(root, false);
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Removing unnecessary override.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java [hunk 10]
```diff
@@ -67,7 +67,7 @@ public ClassPathResult(
   }
 
   /** Returns problems encountered while constructing the dependency graph. */
-  ImmutableList<UnresolvableArtifactProblem> getArtifactProblems() {
+  public ImmutableList<UnresolvableArtifactProblem> getArtifactProblems() {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java]: This function is now used by LinkageCheckerRule

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerArguments.java [hunk 11]
```diff
@@ -200,7 +202,13 @@ private static Options configureOptions() {
 
     if (commandLine.hasOption("b") || commandLine.hasOption("a")) {
       List<Artifact> artifacts = getArtifacts();
-      cachedInputClasspath = classPathBuilder.resolve(artifacts).getClassPath();
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerArguments.java]: This method "resolve" does not throw RepositoryException any more.

Handling the unresolved artifact error by checking `result.getArtifactProblems()`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 12]
```diff
@@ -216,38 +208,90 @@ private DependencyNode resolveCompileTimeDependencies(
    *
    * @param artifacts Maven artifacts to retrieve their dependencies
    * @return dependency graph representing the tree of Maven artifacts
-   * @throws RepositoryException when there is a problem resolving or collecting dependencies
    */
-  public DependencyGraphResult getStaticLinkageCheckDependencyGraph(List<Artifact> artifacts)
-      throws RepositoryException {
+  public DependencyGraphResult buildLinkageCheckDependencyGraph(List<Artifact> artifacts) {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: renamed this method to follow other method "build..."

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 13]
```diff
@@ -216,38 +208,90 @@ private DependencyNode resolveCompileTimeDependencies(
...
+    return buildDependencyGraph(
+        ImmutableList.of(new DefaultDependencyNode(dependency)), GraphTraversalOption.NONE);
+  }
+
+  private DependencyGraphResult buildDependencyGraph(
+      List<DependencyNode> dependencyNodes, GraphTraversalOption traversalOption) {
+    boolean includeProvidedScope =
+        traversalOption == GraphTraversalOption.FULL_DEPENDENCY_WITH_PROVIDED;
+    DependencyNode node;
+    ImmutableSet.Builder<UnresolvableArtifactProblem> artifactProblems = ImmutableSet.builder();
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Set to remove duplicates.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 14]
```diff
@@ -216,38 +208,90 @@ private DependencyNode resolveCompileTimeDependencies(
...
+      return new UnresolvableArtifactProblem(paths.get(0));
+    }
+  }
+
+  private static ImmutableList<List<DependencyNode>> findArtifactPaths(
+      DependencyNode root, Artifact artifact) {
+    String coordinates = Artifacts.toCoordinates(artifact);
+    DependencyFilter filter =
+        (node, parents) ->
+            node.getArtifact() != null
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: artifact is null at a root dummy node.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 15]
```diff
@@ -345,8 +386,6 @@ private DependencyGraphResult levelOrder(
                 artifactProblems.add(new UnresolvableArtifactProblem(fullPath));
               }
             }
-          } catch (DependencyCollectionException collectionException) {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: This exception is no longer thrown.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 16]
```diff
@@ -365,7 +404,14 @@ private DependencyGraphResult levelOrder(
       Stack<DependencyNode> parentNodes, DependencyNode failedDependencyNode) {
     List<DependencyNode> fullPath = new ArrayList<>();
     fullPath.addAll(parentNodes);
-    fullPath.add(failedDependencyNode);
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: testBuildLinkageCheckDependencyGraph_catchRootException revealed that sometimes there was duplicate element in dependency path. For example:

```
xerces:xerces-impl:jar:2.6.2 was not resolved. Dependency path: ant:ant:jar:1.6.2 (compile) > xerces:xerces-impl:jar:2.6.2 (compile?) > xerces:xerces-impl:jar:2.6.2 (compile?)
```

File: dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderTest.java [hunk 17]
```diff
@@ -234,14 +233,34 @@ public void testConfigureAdditionalMavenRepositories_notToUseMavenCentral()
...
+
+    Truth.assertThat(problems).hasSize(2);
+    Truth.assertThat(problems)
+        .comparingElementsUsing(
+            Correspondence.transforming(UnresolvableArtifactProblem::toString, "has description"))
+        .containsExactly(
+            "xerces:xerces-impl:jar:2.6.2 was not resolved. Dependency path: ant:ant:jar:1.6.2"
+                + " (compile) > xerces:xerces-impl:jar:2.6.2 (compile?)",
+            "xml-apis:xml-apis:jar:2.6.2 was not resolved. Dependency path: ant:ant:jar:1.6.2"
+                + " (compile) > xml-apis:xml-apis:jar:2.6.2 (compile?)");
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderTest.java]: xerces-impl and xml-apis are not available (in Maven Central).

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java (hunk 1 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java]: Good idea, though it's a little easier if this sort of change can happen in its own PR that takes less time to review and approve

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java [hunk 18]
```diff
@@ -58,25 +58,29 @@ public ClassPathBuilder(DependencyGraphBuilder dependencyGraphBuilder) {
...
     List<DependencyPath> dependencyPaths = result.getDependencyGraph().list();
 
     // To remove duplicates on (groupId:artifactId) for dependency mediation
     Map<String, String> keyToFirstArtifactVersion = Maps.newHashMap();
 
     for (DependencyPath dependencyPath : dependencyPaths) {
       Artifact artifact = dependencyPath.getLeaf();
-      Path jarAbsolutePath = artifact.getFile().toPath().toAbsolutePath();
+      File file = artifact.getFile();
+      if (file == null) {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java]: not sure, but what if a file is not found for foo:bar:21.6 but we already have foo:bar:24.8 in the graph? Do we still record an unresolved artifact problem? Does this method still work?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerArguments.java [hunk 19]
```diff
@@ -200,7 +202,13 @@ private static Options configureOptions() {
...
+      ClassPathResult result = classPathBuilder.resolve(artifacts);
+      ImmutableList<UnresolvableArtifactProblem> artifactProblems = result.getArtifactProblems();
+      if (!artifactProblems.isEmpty()) {
+        throw new RepositoryException(
+            "Unresolved artifacts: " + Joiner.on(",").join(artifactProblems));
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerArguments.java]: should probably add a space after the comma in the joiner

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java [hunk 20]
```diff
@@ -78,4 +81,44 @@ public static String formatProblems(Iterable<ArtifactProblem> problems) {
...
+    if (other == null || getClass() != other.getClass()) {
+      return false;
+    }
+
+    ArtifactProblem otherProblem = (ArtifactProblem) other;
+    return Objects.equals(artifact, otherProblem.artifact)
+        && sameDependencyPath(dependencyPath, otherProblem.dependencyPath);
+  }
+
+  private static boolean sameDependencyPath(
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java]: Any chance this method belongs in DependencyPath?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 9 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: What was being overridden? Or did you mean overload?
Also, is this removal dependent on this PR or could it be done separately?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 14 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: This would be more useful as a code comment than a review comment.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 9 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Overload, yes.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java (hunk 18 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathBuilder.java]: Yes, that unavailable artifacts are recorded in `result.getArtifactProblems()`.

Created the followup. https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1215

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java (hunk 20 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java]: `com.google.cloud.tools.opensource.dependencies.DependencyPath` does not use `ImmutableList<DependencyNode>`. It uses `List<Dependency>`. So this method should be in DependencyPath.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerArguments.java (hunk 19 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerArguments.java]: Added

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java (hunk 20 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java]: This method eeems like it works with both mutable and immutable lists.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/ArtifactProblem.java]: Yes. Updated. Also renamed to `equalsOnDependencies` as "same" implies checking object identity.

```
  private static boolean equalsOnDependencies(
      List<DependencyNode> listA, List<DependencyNode> listB) {
```

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 9 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Reverted irrelevant refactoring.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java (hunk 14 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: Added source code comment.
