### PR TITLE
FixedSizeClassPathRepository to avoid memory issue

### LINKED ISSUE #653: spring-cloud-gcp memory issue
Thanks to ConstantUtf8 cache (my local modification with `MAX_CACHE_ENTRIES=2000000` and `bcel.maxcached.size=200`), "Spring Cloud GCP Autoconfigure Module" in spring-cloud-gcp does not fail with "OutOfMemoryError: GC overhead limit exceeded".

However, even with the ConstantUtf8 cache , the enforcer rule applied on [spring-cloud-gcp project](https://github.com/spring-cloud/spring-cloud-gcp/tree/linkage-checker) fails at spring-cloud-gcp-kotlin-app-sample (the last module in spring-cloud-gcp):

image

JProfiler shows 606 MB is used for `LinkedHashMap$Entry` instances. The biggest entries are held by `SymbolReferenceMaps`' `ImmutableSetMultimap.Builder`.

image

# Memo

Maven option to let a debugger attach the process:
```
export MAVEN_OPTS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
```

Maven option to heapdump upon OutOfMemoryError:
```
 export MAVEN_OPTS='-XX:+HeapDumpOnOutOfMemoryError'
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #653 

- FixedSizeClassPathRepository maintains fixed-size cache
- It remembers class file name if it does not match class name

# Improvement

- No OutOfMemoryError when the enforcer rule is applied to spring-cloud-gcp (No need to cache BCEL's `ConstantUtf8`)
- Surefire plugin only needs 1GB memory
- Test speed improvement
  - Circle CI: [6:23](https://circleci.com/gh/GoogleCloudPlatform/cloud-opensource-java/1741) -> [2:42](https://circleci.com/gh/GoogleCloudPlatform/cloud-opensource-java/1738)
  - Kokoro Mac OS 12 mins -> 7mins
  - Kokoro Windows 15 mins -> 8 mins

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/NoCachingClassPathRepository.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+import org.apache.bcel.util.ClassPath;
+import org.apache.bcel.util.ClassPathRepository;
+
+/**
+ * This repository behaves same as {@link ClassPathRepository} except that it does not remember
+ * class at all.
+ */
+final class NoCachingClassPathRepository extends ClassPathRepository {
+
+  public NoCachingClassPathRepository(final ClassPath path) {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/NoCachingClassPathRepository.java]: don't need a public constructor in non-public class

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/NoCachingClassPathRepository.java]: Sorry, this file was not need.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 2]
```diff
@@ -339,6 +338,12 @@ Path findClassLocation(String className) {
     return pathToClasses.build();
   }
 
+  /**
+   * Returns a list of class file names in {@code jar} as in {@link JavaClass#getFileName()}. This
+   * class file name is a path ("." as element separator) that locates a class file in a class path.
+   * Usually class name and class file name are the same for a class. However a class file name may
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Usually the class name and class file name are the same. However

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 3]
```diff
@@ -339,6 +338,12 @@ Path findClassLocation(String className) {
...
+   * have a framework-specific prefix. Example: {@code BOOT-INF.classes.com.google.Foo}.
+   */
   static ImmutableSet<String> listClassNamesInJar(Path jar) throws IOException {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: It looks like this method should be named listClassFileNames since it class file names and class names are not the same thing. Also, we probably don't need "InJar". In general, method names don't need to mention their arguments.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 4]
```diff
@@ -359,17 +364,23 @@ Path findClassLocation(String className) {
...
       } catch (ClassNotFoundException ex) {
         // We couldn't find the class in the jar file where we found it.
-        throw new IOException("Corrupt jar file " + jar + "; could not load " + className, ex);
+        throw new IOException("Corrupt jar file " + jar + "; could not load " + classFileName, ex);
       } catch (ClassFormatException ex) {
         // We couldn't load the class from the jar file where we found it.
-        throw new IOException("Possible corrupt jar file " + jar + "; could not load " + className
-            + "; " + ex.getMessage(), ex);
+        throw new IOException(
+            "Possible corrupt jar file "
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Why possible here and imply Corrupt above? Probably remove "Possible"

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+import java.util.HashMap;
+import java.util.Map;
+import javax.annotation.Nullable;
+import org.apache.bcel.classfile.JavaClass;
+import org.apache.bcel.util.ClassPath;
+import org.apache.bcel.util.ClassPathRepository;
+
+/**
+ * This repository behaves the same as {@link ClassPathRepository} except that this class limits the
+ * size of its {@link JavaClass} cache at most {@code maximumSize} entries. When the cache reaches
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java]: to at most

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+import com.google.common.cache.CacheBuilder;
+import java.util.HashMap;
+import java.util.Map;
+import javax.annotation.Nullable;
+import org.apache.bcel.classfile.JavaClass;
+import org.apache.bcel.util.ClassPath;
+import org.apache.bcel.util.ClassPathRepository;
+
+/**
+ * This repository behaves the same as {@link ClassPathRepository} except that this class limits the
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java]: delete "behaves the same as {@link ClassPathRepository} except that this class" since that's implied by the type.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java [hunk 7]
```diff
@@ -0,0 +1,116 @@
...
+ * size of its {@link JavaClass} cache at most {@code maximumSize} entries. When the cache reaches
+ * the limit, it evicts entries that have not been used recently.
+ *
+ * <p>This class avoids {@code OutOfMemoryError: gc overhead limit exceeded} that occurs when
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java]: just "{@code OutOfMemoryError}s"

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java [hunk 8]
```diff
@@ -0,0 +1,116 @@
...
+ * parsing too many JAR files to handle with {@link ClassPathRepository} or {@link
+ * org.apache.bcel.util.MemorySensitiveClassPathRepository}, while providing reasonable speed by
+ * caching frequently-used instances.
+ *
+ * <p>The default maximum size is 1000 entries. As per experiments with spring-cloud-gcp project,
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java]: "As per" --> From

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+    this.specialClassFileName = new HashMap<>();
+  }
+
+  @Override
+  public void storeClass(JavaClass javaClass) {
+    String className = javaClass.getClassName();
+    loadedClass.put(className, javaClass);
+    javaClass.setRepository(this);
+
+    String fileName = javaClass.getFileName();
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java]: classFileName since that's what we've used elsewhere

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+
+  @Override
+  @Nullable
+  public JavaClass findClass(String className) {
+    return loadedClass.getIfPresent(className);
+  }
+
+  @Override
+  public JavaClass loadClass(String className) throws ClassNotFoundException {
+    // Check special location for the class; if none, using className to lookup JavaClass.
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java]: Check special location for the class. If it's not found, lookup by className instead.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java [hunk 11]
```diff
@@ -0,0 +1,116 @@
...
+   *       file name different from its class name. Example: {@code com.google.Foo}
+   *   <li>Value: the special class file name as in {@link JavaClass#getFileName()}, a path that
+   *       locates a class file in a class path. Example: {@code BOOT-INF.classes.com.google.Foo}
+   * </ul>
+   *
+   * @see <a
+   *     href="https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html"
+   *     >Spring Boot Reference Guide: The Executable Jar Format</a>
+   */
+  private final Map<String, String> specialClassFileName;
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/FixedSizeClassPathRepository.java]: I think simply `classFileNames`. It should be plural and `special` doesn't say much now that we have the comments to describe this.
