### PR TITLE
LinkageCheckerRule to use ClassPathResult regardless of DependencySection value

### LINKED ISSUE #1372: Enforcer rule integration test is wrong?
I now think `report-only-reachable/pom.xml` should fail. It fails with BOM project with the same dependencies. Why does it succeed?

I noticed this while I was implementing #1371 , the test failed:

```
[INFO] 
[INFO] --- maven-invoker-plugin:3.2.1:run (integration-test) @ linkage-checker-enforcer-rules ---
[INFO] Building: bom-project-error/pom.xml
[INFO] run post-build script verify.groovy
[INFO]           bom-project-error/pom.xml ........................ SUCCESS (21.3 s)
[INFO] Building: fail-build-for-linkage-errors/pom.xml
[INFO] run post-build script verify.groovy
[INFO]           fail-build-for-linkage-errors/pom.xml ............ SUCCESS (55.6 s)
[INFO] Building: bom-project-no-error/pom.xml
[INFO] run post-build script verify.groovy
[INFO]           bom-project-no-error/pom.xml ..................... SUCCESS (6.6 s)
[INFO] Building: report-only-reachable/pom.xml
[INFO] run post-build script verify.groovy
[INFO]   The post-build script did not succeed. assert buildLog.text.contains("No reachable error found")
       |        |    |
       |        |    false
       |        [INFO] Scanning for projects...
       |        [INFO] 
       |        [INFO] ----< com.google.cloud.tools.opensource:test-report-only-reachable >----
       |        [INFO] Building no-such-method-error-example 1.0-SNAPSHOT
       |        [INFO] --------------------------------[ jar ]---------------------------------
       |        [INFO] 
       |        [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ test-report-only-reachable ---
       |        [INFO] Using 'UTF-8' encoding to copy filtered resources.
       |        [INFO] skip non existing resourceDirectory /Users/suztomo/cloud-opensource-java/enforcer-rules/target/it/report-only-reachable/src/main/resources
       |        [INFO] 
       |        [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ test-report-only-reachable ---
       |        [INFO] No sources to compile
       |        [INFO] 
       |        [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ test-report-only-reachable ---
       |        [INFO] Using 'UTF-8' encoding to copy filtered resources.
       |        [INFO] skip non existing resourceDirectory /Users/suztomo/cloud-opensource-java/enforcer-rules/target/it/report-only-reachable/src/test/resources
       |        [INFO] 
       |        [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ test-report-only-reachable ---
       |        [INFO] No sources to compile
       |        [INFO] 
       |        [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ test-report-only-reachable ---
       |        [INFO] No tests to run.
       |        [INFO] 
       |        [INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ test-report-only-reachable ---
       |        [WARNING] JAR will be empty - no content was marked for inclusion!
       |        [INFO] Building jar: /Users/suztomo/cloud-opensource-java/enforcer-rules/target/it/report-only-reachable/target/test-report-only-reachable-1.0-SNAPSHOT.jar
       |        [INFO] 
       |        [INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforce-linkage-checker) @ test-report-only-reachable ---
       |        [ERROR] Linkage Checker rule found 1 reachable error. Linkage error report:
       |        (com.google.guava:guava:20.0) com.google.common.base.Verify's method verify(boolean arg1, String arg2, Object arg3) is not found;
       |          referenced by 1 class file
       |            io.grpc.internal.ServiceConfigInterceptor (io.grpc:grpc-core:1.17.1)
       |         
       |        [WARNING] Rule 0: com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule failed with message:
       |        Failed while checking class path. See above error report.
       |        [INFO] ------------------------------------------------------------------------
       |        [INFO] BUILD FAILURE
       |        [INFO] ------------------------------------------------------------------------
       |        [INFO] Total time:  5.368 s
       |        [INFO] Finished at: 2020-04-24T18:02:30-04:00
       |        [INFO] ------------------------------------------------------------------------
       |        [ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-linkage-checker) on project test-report-only-reachable: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
       |        [ERROR] 
       |        [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
       |        [ERROR] Re-run Maven using the -X switch to enable full debug logging.
       |        [ERROR] 
       |        [ERROR] For more information about the errors and possible solutions, please read the following articles:
       |        [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
       |        Running post-build script: /Users/suztomo/cloud-opensource-java/enforcer-rules/target/it/report-only-reachable/verify.groovy
       /Users/suztomo/cloud-opensource-java/enforcer-rules/target/it/report-only-reachable/build.log
[INFO]           report-only-reachable/pom.xml .................... FAILED (6.6 s)
[INFO] Building: bom-project-no-packaging/pom.xml
[INFO] run post-build script verify.groovy
[INFO]           bom-project-no-packaging/pom.xml ................. SUCCESS (2.5 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 4, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  report-only-reachable/pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Google Cloud Platform Supported Libraries 5.2.1-SNAPSHOT SUCCESS [  0.386 s]
[INFO] BOM Parent 1.0-SNAPSHOT ............................ SUCCESS [  0.014 s]
[INFO] Cloud Platform Supported Libraries Upper Bounds Check 2.0.0-SNAPSHOT SUCCESS [  1.019 s]
[INFO] Cloud Tools Open Source Code Hygiene Tooling 1.3.1-SNAPSHOT SUCCESS [  0.741 s]
[INFO] Maven Dependency Graph Analyzer 1.3.1-SNAPSHOT ..... SUCCESS [ 11.406 s]
[INFO] integration-tests 1.2.0-SNAPSHOT ................... SUCCESS [  1.241 s]
[INFO] Cloud Tools Open Source Code Hygiene Dashboard 1.3.1-SNAPSHOT SUCCESS [  5.358 s]
[INFO] Linkage Checker Enforcer Rule 1.3.1-SNAPSHOT ....... FAILURE [01:39 min]
[INFO] Linkage Monitor 1.3.1-SNAPSHOT ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

# Root Cause

The entrypoint JAR did not include grpc-core. `project.getDependencies()` is not returning the project's direct dependencies first.

Screen Shot 2020-04-27 at 11 58 49

# Another problem

During this investigation I found another problem 1375. The setup of dependencies is very similar among them but the problem is different.

### PR DESCRIPTION
**Pull request by suztomo**
fixes #1372 

Initially this started towards #1369 . By using `ClassPathResult` for non-BOM projects, this PR also found and fixes a bug #1372 .

- For #1369, LinkageCheckerRule needs to access a dependency tree.
- In LinkageCheckerRule, it is not easy to access the tree.
  - For a BOM project (`DependencySection == DEPENDENCY_MANAGEMENT`), it uses ClassPathResult, which has `DependencyPath`s as dependency tree.
  - For a non-BOM project (`DependencySection == DEPENDENCIES`), it uses Maven's `DependencyResolutionResult` as dependency tree.
- For consistency, this PR converts `DependencyResolutionResult` to `ClassPathResult`, so that `DependencyPath`s represent dependency tree for both BOM case and non-BOM case.
  This fixes #1372 , where entry point JARs were not selected correctly.
- When I tried to use DependencyGraphBuilder.levelOrder to do the conversion, I noticed it throws NullPointerException. DependencyPath could not represent a dependency path in Maven project's dependency tree, because DependencyPath was assuming every node in a tree is a dependency, whereas the root of the tree is not a dependency.
- With this PR, DependencyPath can represent a path in Maven project's dependency tree, which Maven enforcer rule generates. The tree's root node is not a dependency (a Maven project, in which you run `mvn` command, is not a dependency).

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 1]
```diff
@@ -262,22 +264,20 @@ public static UnresolvableArtifactProblem createUnresolvableArtifactProblem(
    *
    * @param firstNode node to start traversal
    */
-  private DependencyGraph levelOrder(DependencyNode firstNode) {
+  public static DependencyGraph levelOrder(DependencyNode firstNode) {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java:267]: LinkageCheckerRule uses this to convert Maven's DependencyNode to our DependencyGraph.

**Comment by suztomo** [comment]
Todo: to investigate the change to `DependencyGraph.findUpdates()`.

**Comment by suztomo** [comment]
Todo: debug empty dependency tree in DashboardMain:

Screen Shot 2020-04-28 at 12 21 28

**Comment by suztomo** [comment]
I'll make this ready for review by tomorrow EOD. If this things get too complex, then we'll choose other ways.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java [hunk 2]
```diff
@@ -95,14 +95,15 @@ public String formatDependencyPaths(Iterable<ClassPathEntry> entries) {
...
 
   /**
-   * Returns mapping from the Maven coordinates to class path entries that are in the dependency
-   * tree.
+   * Returns mapping from the Maven coordinates to {@link ClassPathEntry}. The keys are the
+   * coordinates of the direct dependencies of the root nodes in {@link #dependencyPaths}. The
+   * values are all {@link ClassPathEntry}s in the subtree of the key.
    */
-  public ImmutableSetMultimap<String, ClassPathEntry> coordinatesToClassPathEntry() {
+  public ImmutableSetMultimap<String, ClassPathEntry> coordinatesToClassPathEntriesInSubtree() {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java:102]: I'm not sure this method should be renamed like this. In general shorter names are easier to follow. Partly this is confusing because of the use of the ImmutableSetMultimap instead of a more specific class so you're trying to capture details in the method name that really belong in the return type.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 3]
```diff
@@ -25,52 +25,88 @@
...
+  private final List<Dependency> path = new ArrayList<>();
+
+  public DependencyPath(@Nullable Artifact root) {
+    this.root = root;
+  }
 
   @VisibleForTesting
-  public void add(Dependency dependency) {
-    path.add(dependency);
+  public DependencyPath appended(Dependency dependency) {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:51]: "appended" is strangely phrased. Usually this would be a present tense verb.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 4]
```diff
@@ -25,52 +25,88 @@
...
+ * non-root nodes are dependencies.
+ *
+ * <p>The root node is null for the dependency trees generated for multiple artifacts by {@link
+ * DependencyGraphBuilder#buildFullDependencyGraph(List)}; otherwise the root node is not null.
  */
 public final class DependencyPath {
 
-  private List<Dependency> path = new ArrayList<>();
+  // The root of the dependency path. The project root is not a dependency.
+  private final Artifact root;
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:42]: The separation here is confusing and makes this class more complex. Why isn't the root just the first node in the path? At the very least the public API and documentation can present it as such, even if the internal implementation is more complex.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 5]
```diff
@@ -25,52 +25,88 @@
 import java.util.List;
 import java.util.Objects;
 import java.util.stream.Collectors;
+import javax.annotation.Nullable;
 import org.eclipse.aether.artifact.Artifact;
 import org.eclipse.aether.graph.Dependency;
 
 /**
- * Path from the root to a node in a dependency tree, where a node is a dependency.
+ * Path from the root to a node in a dependency tree, where the root node is a Maven artifact and
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:33]: It occurs to me here that paths don't have roots. Can we rewrite this as simply a path without reference to dependency trees? We can still use it in the dependency tree, but this class doesn't need to know that.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 6]
```diff
@@ -25,52 +25,88 @@
...
+    DependencyPath copy = new DependencyPath(root);
+    for (Dependency value : path) {
+      copy.path.add(value);
+    }
+    copy.path.add(dependency);
+    return copy;
   }
 
-  /** Returns the length of the path. */
+  /** Returns the length of the path plus the root. */
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:60]: why is this not just the length of the path? That is, why does the documentation reflect the implementation?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 7]
```diff
@@ -25,52 +25,88 @@
...
   public int size() {
-    return path.size();
+    return path.size() + 1;
   }
 
   /** Returns the artifact in the leaf (the furthest node from the node) of the path. */
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:65]: Returns the artifact at the end of the path

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 8]
```diff
@@ -25,52 +25,88 @@
...
   public Artifact get(int i) {
-    return path.get(i).getArtifact();
+    if (i == 0) {
+      return root;
+    }
+    return path.get(i - 1).getArtifact();
   }
 
   /**
    * Returns the dependency path of the parent node of the leaf. Empty dependency path if the leaf
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:103]: parent node of the leaf --> second to last node in the path

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathResultTest.java [hunk 9]
```diff
@@ -26,36 +26,33 @@
...
+      new DependencyPath(null).appended(new Dependency(artifactB, "compile"));
+  private DependencyPath dependencyPath_B_A =
+      new DependencyPath(null)
+          .appended(new Dependency(artifactB, "compile"))
+          .appended(new Dependency(artifactA, "compile"));
+  private DependencyPath dependencyPath_A_B_A =
+      new DependencyPath(null)
+          .appended(new Dependency(artifactA, "compile"))
+          .appended(new Dependency(artifactB, "compile"))
+          .appended(new Dependency(artifactA, "compile"));
```
[the remark this answers is not in the document]
Comment (elharo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathResultTest.java:52]: should this be named "append"?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 10]
```diff
@@ -25,52 +25,88 @@
...
+  public DependencyPath(@Nullable Artifact root) {
+    this.root = root;
+  }
 
   @VisibleForTesting
-  public void add(Dependency dependency) {
-    path.add(dependency);
+  public DependencyPath appended(Dependency dependency) {
+    DependencyPath copy = new DependencyPath(root);
+    for (Dependency value : path) {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:53]: I see a lot of copying of lists. It looks like appending a single element copies every item in the list, and then appending another element copies every item in the list again. This is probably N^2 performance and might be relevant given the size of some of our trees.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java (hunk 2 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java]: Reverted the renaming.

Right, I suffered from the vague type while I was debugging the purpose of this method. It tries to fetch all JAR files in a subtree of a Maven artifact but the method name was just rephrasing its return type. Updating Javadoc should suffice.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 5 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java]: Updated as `A sequence of Maven artifacts and dependency (scope and optional flag) in between.`

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 4 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:44]: Removed `getRoot()` API in favor of `get(0)`. Now the root and other artifacts are treated the same in `get(int)`.

> Why isn't the root just the first node in the path?

It's because the first node is an artifact (without a dependency). The other nodes are dependencies, carrying scope and optional flag.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 3 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java]: Renamed to `append`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 10 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:55]: levelOrder was already copying the list when building the dependency tree that consists of `DependencyPath`s
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1371/files#diff-659d7bf4148f942fcc1eb60a50a2ee80L275 .

In future, we can abandon `DependencyPath` in favor of our own node class to represent a tree. It would be something similar to Maven's DependencyNode, but with a parent field. Maven's DependencyNode does not know its parent; therefore, given a DependnecyNode, we cannot get the path from the root to the node.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 6 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java]: Reverted the javadoc change.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 7 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java]: Updated

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 8 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java]: Updated.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathResultTest.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassPathResultTest.java]: Renamed this method as append. (I had thought past participle would indicate a clone. If append is more natural to you, that's good.)

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java [hunk 11]
```diff
@@ -25,52 +25,88 @@
...
+    if (root != null) {
+      builder.add(root);
+    }
+    path.stream().map(Dependency::getArtifact).forEach(builder::add);
+    return builder.build();
+  }
+
+  /** Returns the root of the dependency path. */
+  @Nullable
+  public Artifact getRoot() {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java]: Removed getRoot in favor of `get(0)` to treat root and non-root in the same manner in API.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java [hunk 12]
```diff
@@ -95,14 +95,15 @@ public String formatDependencyPaths(Iterable<ClassPathEntry> entries) {
   }
 
   /**
-   * Returns mapping from the Maven coordinates to class path entries that are in the dependency
-   * tree.
+   * Returns mapping from the Maven coordinates to {@link ClassPathEntry}. The keys are the
+   * coordinates of the direct dependencies of the root nodes in {@link #dependencyPaths}. The
+   * values are all {@link ClassPathEntry}s in the subtree of the key.
    */
   public ImmutableSetMultimap<String, ClassPathEntry> coordinatesToClassPathEntry() {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java:102]: Why is this a multimap? Shouldn't each string coordinate such as com.google:foo:32.2 map to exactly one classpath entry?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java [hunk 13]
```diff
@@ -95,14 +95,15 @@ public String formatDependencyPaths(Iterable<ClassPathEntry> entries) {
...
     Builder<String, ClassPathEntry> coordinatesToEntry = ImmutableSetMultimap.builder();
     for (ClassPathEntry path : getClassPath()) {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassPathResult.java:104]: path --> entry

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraph.java [hunk 14]
```diff
@@ -65,8 +65,12 @@ public DependencyGraph() {
   }
 
   void addPath(DependencyPath path) {
-    graph.add(path);
     Artifact leaf = path.getLeaf();
+    if (leaf == null) {
+      // No need to include a path to null root
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraph.java:70]: is this a null root? Looks like a null leaf.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java (hunk 10 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyPath.java:55]: You might do better by copying/cloning the entire list rather than by rebuilding it.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyTreeFormatter.java [hunk 15]
```diff
@@ -31,43 +35,54 @@
...
+      if (currentNode.equals(childPath)) {
+        continue; // root node's parent is the root itself
+      }
+      formatDependencyPathTree(stringBuilder, tree, childPath, depth);
     }
   }
 
   /**
    * Builds ListMultimap that represents a Maven dependency tree of parent-children relationship.
    * Each node in the tree has a corresponding key in the ListMultimap. The value associated with
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyTreeFormatter.java:75]: what is the key? the path to the node?
