### PR TITLE
Remove collectDependencies call in favor of resolveDependencies

### LINKED ISSUE #1204: Our use of collectDependencies and resolveDependencies seems redundant
DependencyGraphBuilder calls  collectDependencies and resolveDependencies. They seem redundant; it needs only resolveDependencies.

```
    /**
     * Collects the transitive dependencies of an artifact and builds a dependency graph. Note that this operation is
     * only concerned about determining the coordinates of the transitive dependencies. To also resolve the actual
     * artifact files, use {@link #resolveDependencies(RepositorySystemSession, DependencyRequest)}.
     * 
     * @param session The repository session, must not be {@code null}.
     * @param request The collection request, must not be {@code null}.
     * @return The collection result, never {@code null}.
     * @throws DependencyCollectionException If the dependency tree could not be built.
     * @see RepositorySystemSession#getDependencyTraverser()
     * @see RepositorySystemSession#getDependencyManager()
     * @see RepositorySystemSession#getDependencySelector()
     * @see RepositorySystemSession#getVersionFilter()
     * @see RepositorySystemSession#getDependencyGraphTransformer()
     * @see #newResolutionRepositories(RepositorySystemSession, List)
     */
    CollectResult collectDependencies( RepositorySystemSession session, CollectRequest request )
        throws DependencyCollectionException;

    /**
     * Collects and resolves the transitive dependencies of an artifact. This operation is essentially a combination of
     * {@link #collectDependencies(RepositorySystemSession, CollectRequest)} and
     * {@link #resolveArtifacts(RepositorySystemSession, Collection)}.
     * 
     * @param session The repository session, must not be {@code null}.
     * @param request The dependency request, must not be {@code null}.
     * @return The dependency result, never {@code null}.
     * @throws DependencyResolutionException If the dependency tree could not be built or any dependency artifact could
     *             not be resolved.
     * @see #newResolutionRepositories(RepositorySystemSession, List)
     */
    DependencyResult resolveDependencies( RepositorySystemSession session, DependencyRequest request )
        throws DependencyResolutionException;
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1204

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java [hunk 1]
```diff
@@ -183,15 +183,13 @@ private DependencyNode resolveCompileTimeDependencies(
     for (RemoteRepository repository : repositories) {
       collectRequest.addRepository(repository);
     }
-    CollectResult collectResult = system.collectDependencies(session, collectRequest);
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilder.java]: This was unnecessary, because resolveDependencies (line 191) `is essentially a combination of {@link #collectDependencies(RepositorySystemSession, CollectRequest)} and {@link #resolveArtifacts(RepositorySystemSession, Collection)}.` as per the [Javadoc](https://maven.apache.org/resolver/maven-resolver-api/apidocs/org/eclipse/aether/RepositorySystem.html#resolveDependencies(org.eclipse.aether.RepositorySystemSession,%20org.eclipse.aether.resolution.DependencyRequest)).
