### PR TITLE
Fix missing appengine errors

### LINKED ISSUE #336: StaticLinkageErrors for appengine not shown in dashboard table
StaticLinkageErrors for appengine not shown in dashboard table

```
Following paths to the jar file from BOM are found in the dependency tree.

com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-bigquery:1.56.0 / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-compute:0.74.0-alpha / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-datastore:1.56.0 / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-dns:0.74.0-alpha / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-resourcemanager:0.74.0-alpha / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-storage:1.56.0 / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-translate:1.56.0 / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64
com.google.cloud:google-cloud-nio:0.74.0-alpha / com.google.cloud:google-cloud-storage:1.56.0 / com.google.cloud:google-cloud-core-http:1.56.0 / com.google.http-client:google-http-client-appengine:1.27.0 / com.google.appengine:appengine-api-1.0-sdk:1.9.64

```

But the table of these artifacts are shown green. Why?

It's because om.google.http-client:google-http-client-appengine:1.27.0 depends on  com.google.appengine:appengine-api-1.0-sdk:1.9.64 with `scope: provided`, and thus 

```
DependencyGraph completeDependencies = artifactInfo.getCompleteDependencies();
```

does not have DependencyPath to  com.google.appengine:appengine-api-1.0-sdk:1.9.64

The dashboard page contains errors for all jars
The artifact report page contains dependency with `DependencyGraphBuilder.getCompleteDependencies`, which does not take `scope: provided`

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #336. Now appengine errors are shown properly even the dependency path contain `scope:provided`:

image

Also artifact report pages stop showing irrelevant dependency paths:

image

"Following paths to the jar file from BOM are found in the dependency tree." is now showing only relevant paths to the artifact, meaning that the first element is the artifact of the report.

### CODE REVIEW

**Comment by suztomo** [comment]
In an artifact report, compared to irrelevant paths, relevant paths have the Maven artifact in its first element.

Current artifact reports (master) unnecessarily show both relevant paths and irrelevant paths for a jar file. The former is marked as bold.

File: dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java [hunk 1]
```diff
@@ -235,7 +248,7 @@ private static ArtifactResults generateArtifactReport(
       Artifact artifact,
       ArtifactInfo artifactInfo,
       List<DependencyGraph> globalDependencies,
-      ImmutableMap<Path, JarLinkageReport> jarToLinkageReport,
+      Collection<JarLinkageReport> staticLinkageCheckReports,
```
Comment (elharo) [inline dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: This is really any collection, not something more specific like a list or a set?

File: dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java [hunk 2]
```diff
@@ -172,14 +184,15 @@ static Configuration configureFreemarker() {
...
           ArtifactResults results =
               generateArtifactReport(
                   configuration,
                   output,
-                  entry.getKey(),
+                  artifact,
                   entry.getValue(),
                   cache.getGlobalDependencies(),
-                  jarToLinkageReport,
+                  artifactToLinkageReports.get(artifact.toString()),
```
Comment (elharo) [inline dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: toString is less than ideal as a key because it tends to change. We may want a more specific method here such as `getCoordinates`.

Comment (suztomo) [reply dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: Updated to `Artifacts.toCoordinates(artifact)`

File: dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java (hunk 1 above)
Comment (suztomo) [reply dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: Now it's `Set`, after changing `ImmutableMultimap` to more specific `ImmutableSetMultimap` in the caller.

File: dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java [hunk 3]
```diff
@@ -260,13 +272,6 @@ private static ArtifactResults generateArtifactReport(
 
       List<DependencyPath> dependencyPaths = completeDependencies.list();
 
-      // Filter only relevant static linkage report to this artifact and its dependencies
```
Comment (suztomo) [inline dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: This filtering is done at the caller (line 165 of `DashboardMain`) now.
