### PR TITLE
The enforcer rule was not interpreting Path from XML correctly

### LINKED ISSUE #1343: ExclusionFile for LinkageCheckerRule needs to have correct setter name.
To suppress linkage errors using [Linkage Checker Exclusion File](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/Linkage-Checker-Exclusion-File), set `exclusionFile` element to the exclusion file.

```xml
  <LinkageCheckerRule
      implementation="com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule">
      <exclusionFilterFile>linkage-checker-exclusion-rules.xml</exclusionFilterFile>
  </LinkageCheckerRule>
```

It gives the following error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce
 (enforce-linkage-checker) on project no-such-method-error-example: Unable to parse configuration
 of mojo org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce for parameter 
exclusionFilterFile: Cannot find 'exclusionFilterFile' in class 
com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule -> [Help 1]
```

Setting `<exclusionFile>` element also fails:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce 
(enforce-linkage-checker) on project no-such-method-error-example: Unable to parse configuration
 of mojo org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce for parameter exclusionFile:
 Cannot create instance of interface java.nio.file.Path: java.nio.file.Path.<init>() -> [Help 1]
[ERROR] 

```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1343

### CODE REVIEW

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 1]
```diff
@@ -103,7 +103,7 @@
    */
   private boolean reportOnlyReachable = false;
 
-  private Path exclusionFile = null;
+  private String exclusionFile = null;
```
Comment (suztomo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java:106]: This was failing:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce (enforce-linkage-checker) on project no-such-method-error-example: Unable to parse configuration of mojo org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M3:enforce for parameter exclusionFile: Cannot create instance of interface java.nio.file.Path: java.nio.file.Path.<init>() -> [Help 1]
[ERROR] 

```

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 2]
```diff
@@ -126,8 +126,8 @@ void setReportOnlyReachable(boolean reportOnlyReachable) {
   }
 
   @VisibleForTesting
```
Comment (elharo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java:128]: Is this just visible for testing if the name matters for correct XML processing? That is, is some pieve of Maven invoking this method when parsing the pom.xml?

Comment (suztomo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java:128]: It's just visible for testing. Maven enforcer rule  plugin does not use the setter. (So the setter name change was not directly fixing the bug; but it's for consistency).
