### PR TITLE
LinkageCheckerArguments.getArtifacts to return empty list if the argument is not specified

### LINKED ISSUE #1340: LinkageCheckerMain fails to check list of JAR files in v1.1.4
Argument: `-j dependencies/src/test/resources/testdata/google-cloud-core-1.48.0.jar,dependencies/src/test/resources/testdata/google-cloud-firestore-0.65.0-beta.jar`. This fails:

```
Exception in thread "main" java.lang.IllegalArgumentException: The arguments must have option 'a' or 'b' to list Maven artifacts
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerArguments.getArtifacts(LinkageCheckerArguments.java:182)
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:54)

```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1340

### CODE REVIEW

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+    Path googleCloudCore = absolutePathOfResource("testdata/google-cloud-core-1.48.0.jar");
+    Path googleCloudFirestore =
+        absolutePathOfResource("testdata/google-cloud-firestore-0.65.0-beta.jar");
+    Path guava = absolutePathOfResource("testdata/guava-23.5-jre.jar");
+
+    String jarArgument = googleCloudCore + "," + googleCloudFirestore + "," + guava;
+
+    // This should not raise Exception
+    LinkageCheckerMain.main(new String[] {"-j", jarArgument});
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java:65]: This was throwing exception (#1341 )
