### PR TITLE
Uncomment FreemarkerTest cleanup code

### LINKED ISSUE #448: Why doesn't FreemarkerTest delete? in cleanUp?
Either remove the method or uncomment it.

```
public class FreemarkerTest {

  private static Path outputDirectory;
  private Builder builder = new Builder();

  @AfterClass
  public static void cleanUp() throws IOException {
    // MoreFiles.deleteRecursively(outputDirectory, RecursiveDeleteOption.ALLOW_INSECURE);
  }
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #448 . It was accidentally commented out when I was checking the output html.

- uncomment the directory cleanup
- removed ALLOW_INSECURE option when the tests do cleanup. As per [Javadoc](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/io/RecursiveDeleteOption.html#ALLOW_INSECURE), ALLOW_INSECURE is for symbolic links on (insecure) file systems. 
This test does not use symbolic links.

### CODE REVIEW

File: dashboard/src/test/java/com/google/cloud/tools/opensource/dashboard/FreemarkerTest.java [hunk 1]
```diff
@@ -61,7 +63,7 @@ public static void setUp() throws IOException {
 
   @AfterClass
   public static void cleanUp() throws IOException {
-    // MoreFiles.deleteRecursively(outputDirectory, RecursiveDeleteOption.ALLOW_INSECURE);
+    MoreFiles.deleteRecursively(outputDirectory);
```
Comment (suztomo) [inline dashboard/src/test/java/com/google/cloud/tools/opensource/dashboard/FreemarkerTest.java]: As per [Javadoc](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/io/RecursiveDeleteOption.html#ALLOW_INSECURE), ALLOW_INSECURE is for symbolic links on (insecure) file systems. 
This test does not use symbolic links.
