### PR TITLE
avoid polluting local repository

### LINKED ISSUE #1301: DependencyGraphBuilderTest.testConfigureAdditionalMavenRepositories_notToUseMavenCentral is flaky
Normal usage installs the test dependency into the local repo which causes the test to fail. Perhaps use a different, temporary local repo for the test?

[ERROR]   DependencyGraphBuilderTest.testConfigureAdditionalMavenRepositories_notToUseMavenCentral:224 expected to contain: com.google.guava:guava:15.0-rc1
testing whether    : actual element has artifact expected element
but was            : []

### PR DESCRIPTION
**Pull request by elharo**
fixes #1301

This injects a local repository into the graph builder from the test, so we avoid installing any artifacts into `~.m2`

Suggestions for making this less hacky appreciated.

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtility.java [hunk 1]
```diff
@@ -122,9 +122,8 @@ static DefaultRepositorySystemSession createDefaultRepositorySystemSession(
    * customary ~/.m2 directory. If not found, it creates an initially empty repository in
    * a temporary location.
    */
-  public static RepositorySystemSession newSession(RepositorySystem system) {
+  public static DefaultRepositorySystemSession newSession(RepositorySystem system) {
     DefaultRepositorySystemSession session = createDefaultRepositorySystemSession(system);
-    session.setReadOnly();
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtility.java:127]: I think setting we want to set the maven directory in createDefaultRepositorySystemSession to keep the returned session read-only.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderIntegrationTest.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+public class DependencyGraphBuilderIntegrationTest {
+
+  private Correspondence<UnresolvableArtifactProblem, String> problemOnArtifact =
+      Correspondence.transforming(
+          (UnresolvableArtifactProblem problem) -> Artifacts.toCoordinates(problem.getArtifact()),
+          "has artifact");
+
+  @Test
+  public void testConfigureAdditionalMavenRepositories_notToUseMavenCentral() {
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/dependencies/DependencyGraphBuilderIntegrationTest.java:36]: Now this test passes. Thank you.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtility.java (hunk 1 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtility.java:127]: I'm not sure that's necessary. Is there some reason it has to be read-only?

I did try setting it here, but the extra code to configure it from the test was even uglier since DependencyGraphBuilderIntegrationTest doesn't directly access RepositoryUtility.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/dependencies/RepositoryUtility.java:127]: OK. Then this current code is good.
