### PR TITLE
Skip corrupt class file in JAR rather than stopping

### LINKED ISSUE #1048: Beam: Linkage Checker gets corrupt JAR file error from amazon-kinesis-client
Investigate whether this kind of corruption is skipped or not.

```
suztomo@suxtomo24:~/beam6$ ./gradlew -Ppublishing -PjavaLinkageArtifactIds=beam-sdks-java-io-kinesis :checkJavaLinkage |tee linkage.log
Configuration on demand is an incubating feature.

> Task :runners:apex:buildDependencyTree
See the report at: file:///usr/local/google/home/suztomo/beam6/runners/apex/build/classes/java/main/org/apache/beam/runners/apex/dependency-tree

> Task :checkJavaLinkage

> Task :checkJavaLinkage FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings
885 actionable tasks: 156 executed, 729 up-to-date
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.io.IOException: Corrupt jar file /usr/local/google/home/suztomo/.m2/repository/com/amazonaws/amazon-kinesis-client/1.13.0/amazon-kinesis-client-1.13.0.jar; could not load .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp.amazonaws.services.kinesis.leases.impl.LeaseTaker
        at com.google.cloud.tools.opensource.classpath.ClassDumper.listClasses(ClassDumper.java:393)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.findSymbolReferences(ClassDumper.java:153)
        at com.google.cloud.tools.opensource.classpath.LinkageChecker.create(LinkageChecker.java:78)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:49)
Caused by: java.lang.ClassNotFoundException: Exception while looking for class .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp.amazonaws.services.kinesis.leases.impl.LeaseTaker: java.io.IOException: Couldn't find: /unison/com/e007f77498fd27177e2ea931a06dcf50/unison/tmp/amazonaws/services/kinesis/leases/impl/LeaseTaker.class
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:77)
        at org.apache.bcel.util.ClassPathRepository.loadClass(ClassPathRepository.java:31)
        at com.google.cloud.tools.opensource.classpath.FixedSizeClassPathRepository.loadClass(FixedSizeClassPathRepository.java:108)
        at com.google.cloud.tools.opensource.classpath.ClassDumper.listClasses(ClassDumper.java:389)
        ... 3 more
Caused by: java.io.IOException: Couldn't find: /unison/com/e007f77498fd27177e2ea931a06dcf50/unison/tmp/amazonaws/services/kinesis/leases/impl/LeaseTaker.class
        at org.apache.bcel.util.ClassPath.getClassFile(ClassPath.java:666)
        at com.google.cloud.tools.opensource.classpath.LinkageCheckClassPath.getInputStream(LinkageCheckClassPath.java:72)
        at org.apache.bcel.util.ClassPath.getInputStream(ClassPath.java:688)
        at org.apache.bcel.util.AbstractClassPathRepository.loadClass(AbstractClassPathRepository.java:75)
        ... 6 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkJavaLinkage'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1048 .

Initially I thought outputting warning message per file but it turned out there are many of them (220) in the artifact. Now the implementation outputs one warning per JAR file:

```
Jan 07, 2020 1:33:51 PM com.google.cloud.tools.opensource.classpath.ClassDumper listClasses
WARNING: Corrupt jar file /usr/local/google/home/suztomo/.m2/repository/com/amazonaws/amazon-kinesis-client/1.13.0/amazon-kinesis-client-1.13.0.jar; could not load .unison.com.e007f77498fd27177e2ea931a06dcf50.unison.tmp.amazonaws.services.kinesis.leases.impl.LeaseTaker and other 219 files

```

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 1]
```diff
@@ -395,7 +400,16 @@ Path findClassLocation(String className) {
...
-        throw new IOException("Corrupt jar file " + jar + "; could not load " + classFileName, ex);
+        Throwable cause = ex.getCause();
+        if (cause != null && cause instanceof IOException) {
+          // Skip unexpected files (such as a lock file) included in JAR file
+          // https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1048 was caused
+          // by an IOException
+          corruptedClassFileNames.add(classFileName);
+        } else {
+          throw new IOException(
+              "Corrupt jar file " + jar + "; could not load " + classFileName, ex);
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: so we'll still die on these sorts of corrupt jar files? Is that what we want? Perhaps whoever calls this method should handle the IOExceptions that arise here.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: That's a nice idea. Now `findSymbolReferences` catches the exception.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java [hunk 2]
```diff
@@ -313,7 +314,8 @@ public void testIsUnusedClassSymbolReference_classSymbolReferenceNotFound()
             ImmutableList.of(absolutePathOfResource("testdata/conscrypt-openjdk-uber-1.4.2.jar")));
 
     try {
-      classDumper.isUnusedClassSymbolReference("org.conscrypt.Conscrypt", new ClassSymbol("dummy.NoSuchClass"));
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: This was exceeding 100 char limit.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 1 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: I found the problem of catching IOException at the caller; it would skip all _valid_ classes in the JAR file.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 3]
```diff
@@ -395,7 +400,7 @@ Path findClassLocation(String className) {
         javaClasses.add(javaClass);
       } catch (ClassNotFoundException ex) {
         // We couldn't find the class in the jar file where we found it.
-        throw new IOException("Corrupt jar file " + jar + "; could not load " + classFileName, ex);
+        corruptedClassFileNames.add(classFileName);
       } catch (ClassFormatException ex) {
         // We couldn't load the class from the jar file where we found it.
         throw new IOException(
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: could we bubble the ClassFormatException instead? This isn't really an IO error.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java [hunk 4]
```diff
@@ -364,4 +366,26 @@ public void testFindSymbolReferences_overLappingClass() throws IOException, Repo
...
+    // This should not raise IOException
+    SymbolReferenceMaps symbolReferences = classDumper.findSymbolReferences();
+    assertNotNull(symbolReferences);
+
+    Truth.assertWithMessage("Invalid files should not stop loading valid class files")
+        .that(symbolReferences.getClassToClassSymbols().keySet())
+        .comparingElementsUsing(
+            Correspondence.transforming(
+                (ClassFile classFile) -> classFile.getJar(), "is in the JAR file"))
+        .contains(kinesisJar);
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: This asserts that ClassDumper loads valid class files from the JAR file even if some of the content are invalid files.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 3 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Yes, removed the catch clause.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: It turned out that this change causes #1142.
