### PR TITLE
LinkageCheckerMainIntegrationTest.testArtifacts to use newer google-cloud-firestore that has no auto-value dependency

### LINKED ISSUE #1828: LinkageCheckerMainIntegrationTest.testArtifacts fails in Java 11
```
$ mvn test -Dtest=LinkageCheckerMainIntegrationTest#testArtifacts
...
[ERROR] testArtifacts(com.google.cloud.tools.opensource.classpath.LinkageCheckerMainIntegrationTest)  Time elapsed: 2.129 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<Found 7[5] linkage errors> but was:<Found 7[7] linkage errors>
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerMainIntegrationTest.testArtifacts(LinkageCheckerMainIntegrationTest.java:96)
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1828 . The result of `LinkageCheckerMainIntegrationTest.testArtifacts` differed between Java 8 and Java 11, because:
- `google-cloud-firestore:0.65.0-beta` has unexpected auto-value dependency that has references to  `javax.annotation.Generated`.
- The `javax.annotation.Generated` has been removed in Java 11.

Here are the linkage errors for the artifact before and after:

- Linkage Errors before the change (with 0.65.0-beta): https://gist.github.com/suztomo/b0a19b75b2a79960ab4a978b4ba70c8d
- Linkage Errors after the change (with 1.35.2): https://gist.github.com/suztomo/9a44b2d6994200fd5fe3110830e0e01b 

The linkage errors are from the grpc-netty-shaded and logger. Different versions of this library contains different number of missing classes.

### CODE REVIEW

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java [hunk 1]
```diff
@@ -90,10 +90,11 @@ public void testArtifacts()
       throws IOException, RepositoryException, TransformerException, XMLStreamException {
     try {
       LinkageCheckerMain.main(
-          new String[] {"-a", "com.google.cloud:google-cloud-firestore:0.65.0-beta"});
+          // protobuf-java:3.13.0 in
+          new String[] {"-a", "com.google.cloud:google-cloud-firestore:1.35.2"});
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java:94]: Why not the latest 2.1.0? It's because the latest version has dependency to protobuf-java:3.13.0, which also have different results between Java 8 and Java 11.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java [hunk 2]
```diff
@@ -102,15 +103,14 @@ public void testArtifacts()
             "Class com.jcraft.jzlib.JZlib is not found;\n"
                 + "  referenced by 4 class files\n"
                 + "    io.grpc.netty.shaded.io.netty.handler.codec.spdy.SpdyHeaderBlockJZlibEncoder"
-                + " (io.grpc:grpc-netty-shaded:1.13.1)");
+                + " (io.grpc:grpc-netty-shaded:1.30.2)");
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java:106]: Diff:

Linkage Errors before the change (with 0.65.0-beta): https://gist.github.com/suztomo/b0a19b75b2a79960ab4a978b4ba70c8d
Linkage Errors after the change (with 1.35.2): https://gist.github.com/suztomo/9a44b2d6994200fd5fe3110830e0e01b

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java [hunk 3]
```diff
@@ -90,10 +90,11 @@ public void testArtifacts()
       throws IOException, RepositoryException, TransformerException, XMLStreamException {
     try {
       LinkageCheckerMain.main(
-          new String[] {"-a", "com.google.cloud:google-cloud-firestore:0.65.0-beta"});
+          // protobuf-java:3.13.0 in
+          new String[] {"-a", "com.google.cloud:google-cloud-firestore:1.35.2"});
       fail("LinkageCheckerMain should throw LinkageCheckResultException upon errors");
     } catch (LinkageCheckResultException expected) {
-      assertEquals("Found 75 linkage errors", expected.getMessage());
+      assertEquals("Found 76 linkage errors", expected.getMessage());
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java:97]: Diff:

Linkage Errors before the change (with 0.65.0-beta): https://gist.github.com/suztomo/b0a19b75b2a79960ab4a978b4ba70c8d
Linkage Errors after the change (with 1.35.2): https://gist.github.com/suztomo/9a44b2d6994200fd5fe3110830e0e01b

**Review by elharo — APPROVED** [review]
Makes sense. Good fix.
