### PR TITLE
Use a single ImmutableList<Path> type

### LINKED ISSUE #254: Refactor StaticLinkageCheckOption
It's only really used in one place. The purpose is to produce an `ImmutableList<Path>`:

```
  @VisibleForTesting
  static ImmutableList<Path> generateInputClasspathFromLinkageCheckOption(
      StaticLinkageCheckOption linkageCheckOption) throws RepositoryException {
    ImmutableList.Builder<Path> jarFileBuilder = ImmutableList.builder();

    // TODO(suztomo): add logic to convert Maven BOM to list of Maven coordinates as per README.md
    jarFileBuilder.addAll(linkageCheckOption.getJarFiles());
    for (String mavenCoordinates : linkageCheckOption.getArtifacts()) {
      jarFileBuilder.addAll(coordinatesToClasspath(mavenCoordinates));
    }
    return jarFileBuilder.build();
  }
```

What we may need is three static methods that take as input a BOM, list of maven coordinates, or list of jar files respectively and return an `ImmutableList<Path>` for each case.

### PR DESCRIPTION
**Pull request by elharo**
so we don't need the effective union type StaticLinkageCheckOption

@netdpb fix #254

### CODE REVIEW

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOptionTest.java [hunk 1]
```diff
@@ -16,72 +16,41 @@
...
+    CommandLine parsedOption = StaticLinkageCheckOption.readCommandLine(arguments);
 
-    Assert.assertEquals(ImmutableList.of("abc.com:abc:1.1", "abc.com:abc-util:1.2"),
-        parsedOption.getArtifacts());
-    Assert.assertTrue(parsedOption.isReportOnlyReachable());
+    Assert.assertEquals("abc.com:dummy:1.2", parsedOption.getOptionObject('b'));
   }
 
   @Test
   public void parseCommandLineOptions_duplicates() throws ParseException {
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOptionTest.java]: This function does not seem to throw ParseException any more.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java [hunk 2]
```diff
@@ -16,23 +16,22 @@
...
 import java.util.stream.Stream;
-import javax.annotation.Nullable;
 import org.apache.commons.cli.CommandLine;
 import org.apache.commons.cli.CommandLineParser;
 import org.apache.commons.cli.DefaultParser;
 import org.apache.commons.cli.HelpFormatter;
 import org.apache.commons.cli.Options;
 import org.apache.commons.cli.ParseException;
+import org.eclipse.aether.RepositoryException;
+
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java]: As discussed earlier, let's avoid changing import order from new one to old in existing files, (and vice versa).

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOptionTest.java (hunk 1 above)
Comment (elharo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOptionTest.java]: done

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java (hunk 2 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java]: done

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java [hunk 3]
```diff
@@ -105,45 +88,35 @@ static StaticLinkageCheckOption parseArguments(String[] arguments) throws ParseE
...
-                .collect(Collectors.toList());
-        jarFilePaths.addAll(jarFilesInArguments);
-      }
-
+      return jarFileBuilder.build();
+    } else if (commandLine.hasOption("j")) {
+      String jarFiles = commandLine.getOptionValue("j");
+      List<Path> jarFilesInArguments =
+          Streams.stream(commaSplitter.split(jarFiles))
+              .map(name -> (Paths.get(name)).toAbsolutePath())
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java]: You don't need the extra parentheses here.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java [hunk 4]
```diff
@@ -105,45 +88,35 @@ static StaticLinkageCheckOption parseArguments(String[] arguments) throws ParseE
...
+              .collect(Collectors.toList());
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java]: `ImmutableList.toImmutableList()` lets you collect directly into an `ImmutableList`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java [hunk 5]
```diff
@@ -105,45 +88,35 @@ static StaticLinkageCheckOption parseArguments(String[] arguments) throws ParseE
...
-          .setJarFiles(jarFilePaths)
-          .setReportOnlyReachable(reportOnlyReachable)
-          .build();
-    } catch (ParseException ex) {
-      HelpFormatter helpFormatter = new HelpFormatter();
-      helpFormatter.printHelp("StaticLinkageChecker", options);
-      throw ex;
+      // TODO(suztomo): add logic to convert Maven BOM to list of Maven coordinates as per README.md
+      
+      return jarFileBuilder.build();
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckOption.java]: Let's not bother with a builder defined outside the if/else, especially since one branch ignores it. Each mutually-exclusive branch can easily stream into an `ImmutableList`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageChecker.java [hunk 6]
```diff
@@ -63,8 +64,8 @@ static StaticLinkageChecker create(
   }
 
   /**
-   * Flag on the reachability. This flag controls whether the report excludes the linkage errors
-   * on classes that are not reachable from the entry points of the class usage graph.
+   * Flag that controls whether the report excludes linkage errors on classes that are not reachable
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageChecker.java]: Can we be explicit about what `true` means? "controls whether it excludes errors that are not reachable" makes my brain hurt.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckerTest.java [hunk 7]
```diff
@@ -162,58 +164,55 @@ public void testFindInvalidReferences_constructorInAbstractClass()
...
+    String[] arguments = {"--jars", "dir1/foo.jar,dir2/bar.jar,baz.jar"};
+    CommandLine parsedOption = StaticLinkageCheckOption.readCommandLine(arguments);
+    List<Path> inputClasspath = StaticLinkageCheckOption.generateInputClasspath(parsedOption);
 
     Truth.assertThat(inputClasspath)
         .comparingElementsUsing(PATH_FILE_NAMES)
         .containsExactly("foo.jar", "bar.jar", "baz.jar");
   }
 
+
```
Comment (netdpb) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckerTest.java]: Delete

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckerTest.java [hunk 8]
```diff
@@ -271,4 +270,5 @@ public void testJarPathOrderInResolvingReferences() throws IOException, ClassNot
         .that(reportWith66First.getMissingMethodErrors())
         .isEmpty();
   }
+
```
Comment (netdpb) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/StaticLinkageCheckerTest.java]: Delete.
