### PR TITLE
don't fail build when level is set to warn

### LINKED ISSUE #555: level WARN still fails the build
```
n: CLASS_NOT_FOUND, target class location not found, isReachable: true
  MethodSymbolReference{sourceClassName=net.bytebuddy.agent.VirtualMachine$ForHotSpot$OnUnix, targetClassName=org.newsclub.net.unix.AFUNIXSocket, methodName=close, interfaceMethod=false, descriptor=()V}, reason: CLASS_NOT_FOUND, target class location not found, isReachable: true


[WARNING] Rule 0: com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule failed with message:
Failed while checking class path. See above error report.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:21 min
[INFO] Finished at: 2019-04-04T12:59:23-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0-M1:enforce (linkage) on project appengine-plugins-core: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### PR DESCRIPTION
**Pull request by elharo**
fixes #555 @garrettjonesgoogle

### CODE REVIEW

File: enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java [hunk 1]
```diff
@@ -155,10 +155,11 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
             logger.warn(message);
           } else {
             logger.error(message);
+            throw new EnforcerRuleException(
+                "Failed while checking class path. See above error report.");
           }
-          throw new EnforcerRuleException(
-              "Failed while checking class path. See above error report.");
         } else {
+          // arguably shouldn't log anything on success
```
Comment (garrettjonesgoogle) [inline enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: Maybe we should convert it to a verbose log?

Comment (elharo) [reply enforcer-rules/src/main/java/com/google/cloud/tools/dependencies/enforcer/LinkageCheckerRule.java]: That's a good idea. I need to check what other enforcer plugins do when the rule passes so we can understand what users expect.
