### PR TITLE
Reachability check via ClassSymbolGraph

### LINKED ISSUE #394: Mockito can't find ant in grpc testing
```
io.grpc:grpc-testing:1.17.1
mockito-core-1.9.5.jar (9 errors):
  ClassSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.Task, subclass=true}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.types.FileSet, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.DirectoryScanner, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.BuildException, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  MethodSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.Task, methodName=<init>, interfaceMethod=false, descriptor=()V}, reason: CLASS_NOT_FOUND, target class location not found
  MethodSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.types.FileSet, methodName=getDirectoryScanner, interfaceMethod=false, descriptor=(Lorg/apache/tools/ant/Project;)Lorg/apache/tools/ant/DirectoryScanner;}, reason: CLASS_NOT_FOUND, target class location not found
  MethodSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.DirectoryScanner, methodName=getIncludedFiles, interfaceMethod=false, descriptor=()[Ljava/lang/String;}, reason: CLASS_NOT_FOUND, target class location not found
  MethodSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.types.FileSet, methodName=getDir, interfaceMethod=false, descriptor=(Lorg/apache/tools/ant/Project;)Ljava/io/File;}, reason: CLASS_NOT_FOUND, target class location not found
  MethodSymbolReference{sourceClassName=org.mockito.cglib.transform.AbstractProcessTask, targetClassName=org.apache.tools.ant.BuildException, methodName=<init>, interfaceMethod=false, descriptor=(Ljava/lang/Throwable;)V}, reason: CLASS_NOT_FOUND, target class location not found
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #394. Mockito's org.mockito.cglib.transform.AbstractProcessTask is not reachable from grpc-testing.

- New `ClassReferenceGraph` to check reachability of a class
- Reachability is an attribute of a `StaticLinkageError` (screenshot below)
- Class reference extraction by `ClasspathChecker` is moved from `findLinkageErrors()` to `create()`. This is to make `classReferenceGraph` instance property as `final`.
- As discussed entry point classes are:
  - **Check for a BOM**: classes in the Maven artifacts listed in the BOM.
  - **Check for a list of Maven artifacts**: classes in the Maven artifacts.
- Deleted `--report-only-reachable` option. This has not been implemented.

image

# Overhead

There's some overhead in adding class reachability check. Here is comparison of time taken by DashboardTest in Circle CI.

### Before:
branch: **master** build: 970 took 35 seconds in DashboardTest

```
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.886 s - in com.google.cloud.tools.opensource.dashboard.DashboardTest
```

### After
branch:**class_graph** build:972 took 38 seconds in DashboardTest

```
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.346 s - in com.google.cloud.tools.opensource.dashboard.DashboardTest
```

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 1]
```diff
@@ -108,14 +118,22 @@ public static void main(String[] arguments)
...
+      jarToSymbolBuilder.put(jarPath, ClassDumper.scanSymbolReferencesInJar(jarPath));
     }
+    ImmutableMap<Path, SymbolReferenceSet> jarToSymbols = jarToSymbolBuilder.build();
+
+    ImmutableSet.Builder<ClassSymbolReference> classReferenceBuilder = ImmutableSet.builder();
+    for (SymbolReferenceSet symbolReferenceSet : jarToSymbols.values()) {
+      classReferenceBuilder.addAll(symbolReferenceSet.getClassReferences());
+    }
+    this.classSymbolGraph = ClassSymbolGraph.create(classReferenceBuilder.build()
+        , entryPoints);
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: The graph can be built here from `SymbolReferenceSet`, making it difficult to make it as `final` instance member.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java [hunk 2]
```diff
@@ -123,21 +129,30 @@ private static Options configureOptions() {
     return options;
   }
 
-  static ImmutableList<Path> generateInputClasspath(CommandLine commandLine)
-      throws RepositoryException, ParseException {
-    setRepositories(commandLine);
-
+  static ImmutableList<Artifact> generateArtifacts(CommandLine commandLine)
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: This method helps to prepare a list of entry point artifacts.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 3]
```diff
@@ -49,33 +49,43 @@
...
-  }
 
-  /**
-   * If true, the report excludes linkage errors on classes that are not reachable
-   * from the entry points of the class usage graph.
-   */
-  private final boolean reportOnlyReachable;
+    ImmutableMap.Builder<Path, SymbolReferenceSet> jarToSymbolBuilder = ImmutableMap.builder();
+    for (Path jarPath : jarPaths) {
+      jarToSymbolBuilder.put(jarPath, ClassDumper.scanSymbolReferencesInJar(jarPath));
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: The logic of scanning jar files and building references has been moved to before constructing `ClasspathChecker`.
This is because the output (class references) is required to create `ClassReferenceGraph` and I wanted to make the `classReferenceGraph` field as `final`, meaning that the class references need to be available before constructing `ClasspathChecker` instance.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java [hunk 4]
```diff
@@ -84,30 +85,35 @@ private static Options configureOptions() {
     options.addOption(
         "b", "bom", true, "BOM to generate a class path, specified by its Maven coordinates");
 
-    Option artifactOption = Option.builder("a").longOpt("artifacts").hasArgs()
-        .valueSeparator(',')
-        .desc("Maven coordinates for Maven artifacts (separated by ',') to generate a class path")
-        .build();
+    Option artifactOption =
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: No change for option "a", "j", "m". Just formatting.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java [hunk 5]
```diff
@@ -84,30 +85,35 @@ private static Options configureOptions() {
...
+            .longOpt("jars")
+            .hasArgs()
+            .valueSeparator(',')
+            .desc("Jar files (separated by ',') to generate a class path")
+            .build();
     options.addOption(jarOption);
 
-    options.addOption(
-        "r",
-        "report-only-reachable",
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: This option has not been implemented, and being removed.

File: dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java [hunk 6]
```diff
@@ -95,12 +95,11 @@ public static Path generate()
     // LinkedListMultimap preserves the key order
     ImmutableList<Path> classpath = ImmutableList.copyOf(jarToDependencyPaths.keySet());
 
-    // TODO(suztomo): choose entry point classes for reachability
-    ImmutableSet<Path> entryPoints = ImmutableSet.of(classpath.get(0));
+    // When checking a BOM, entry point classes are the ones in the artifacts listed in the BOM
+    List<Path> artifactJarsInBom = classpath.subList(0, managedDependencies.size());
+    ImmutableSet<Path> entryPoints = ImmutableSet.copyOf(artifactJarsInBom);
 
-    boolean onlyReachable = false;
```
Comment (elharo) [inline dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: There should still be an option here, and the default should be false; that is, not limit ourselves to "reachable" classes.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+import java.util.Queue;
+import java.util.Set;
+import org.apache.bcel.classfile.JavaClass;
+
+/**
+ * Directed graph of class references. Given classes in {@code entryPointJars}, it provides
+ * {@link #isReachable(String)} for a class to check the reachability. The graph's node and edges
+ * are defined as following:
+ *
+ * <p>Nodes are class names.
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: fully qualified class names

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+ *
+ * <p>Edges are references between two classes. When {@code ClassA} has a reference to {@code
+ * ClassB}, a directed edge from {@code ClassA} to {@code ClassB} exists in the graph. Because
+ * self-loops and parallel edges are unnecessary for reachability checks, they are not allowed.
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: not allowed --> not constructed.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 5 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: we need this though. Per yesterday's discussion we want reachability checking to be configurable.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java [hunk 9]
```diff
@@ -131,6 +131,13 @@ public String formatByGroup() {
               .collect(Collectors.joining(", "));
 
       builder.append("Referenced by: ");
+
+      // Group is marked unreachable if none of the errors in the group is reachable
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]: What is a group in this context?

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java [hunk 10]
```diff
@@ -43,7 +43,7 @@
 import org.junit.Test;
 
 public class ClassDumperTest {
-  private static final String EXAMPLE_JAR_FILE =
+  static final String EXAMPLE_JAR_FILE =
```
Comment (elharo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: why can't this be private?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java (hunk 9 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]: It's LinkageErrorCause.

Added it in comment.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java (hunk 10 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: ClassReferenceGraphTest also uses it.

Renamed it to GRPC_CLOUD_FIRESTORE_JAR to be more specific.

File: dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java (hunk 6 above)
Comment (suztomo) [reply dashboard/src/main/java/com/google/cloud/tools/opensource/dashboard/DashboardMain.java]: This change is to mark the unreachable classes. Nothing is to be filtered based on them.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 5 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: This change is to mark errors unreachable if there is no paths to the class, **without dropping** errors based on the value.

Do you still want configuration?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java (hunk 8 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: Fixed

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java (hunk 7 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: Fixed

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java [hunk 11]
```diff
@@ -0,0 +1,107 @@
...
+      graph.putEdge(sourceClassName, targetClassName);
+    }
+
+    this.reachableClasses = reachableNodes(graph, entryPointClasses);
+  }
+
+  /**
+   * Returns a set of class names reachable from {@code fromNodes} by following edges in the graph.
+   */
+  private static ImmutableSet<String> reachableNodes(Graph<String> graph, Set<String> fromNodes) {
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: Use `Graphs.reachableNodes(Graph<N>, N)`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java [hunk 12]
```diff
@@ -123,21 +129,30 @@ private static Options configureOptions() {
     return options;
   }
 
-  static ImmutableList<Path> generateInputClasspath(CommandLine commandLine)
-      throws RepositoryException, ParseException {
-    setRepositories(commandLine);
-
+  static ImmutableList<Artifact> generateArtifacts(CommandLine commandLine)
+      throws RepositoryException {
+    Preconditions.checkArgument(
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: This is user error, right? I'm not sure `IllegalArgumentException` is the right one. Is there a `ParseException` subclass that's more appropriate? `MissingOptionException`?

(By the way, could you use an `OptionGroup` to make Apache report an error if more than one of `-b`, `-a`, and `-j` is used?)

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java [hunk 13]
```diff
@@ -123,21 +129,30 @@ private static Options configureOptions() {
...
+        commandLine.hasOption("b") || commandLine.hasOption("a"),
+        "The arguments must have option 'a' or 'b' to list Maven artifacts");
     if (commandLine.hasOption("b")) {
       String bomCoordinates = commandLine.getOptionValue("b");
       DefaultArtifact bomArtifact = new DefaultArtifact(bomCoordinates);
-      List<Artifact> artifactsInBom = RepositoryUtility.readBom(bomArtifact);
-      return ClassPathBuilder.artifactsToClasspath(artifactsInBom);
-    } else if (commandLine.hasOption("a")) {
+      return ImmutableList.copyOf(RepositoryUtility.readBom(bomArtifact));
+    } else {
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: If you structured this like so, your logic to throw an exception would be more closely tied to your parsing logic:

```
if has option b:
  // use option b
else if has option a:
  // use option a
else throw exception
```

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 2 above)
Comment (netdpb) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: You're not really _generating_ artifacts. You're reading the artifacts specified on the command line. What about calling this `parseArtifacts` or `getArtifacts` or something?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java [hunk 14]
```diff
@@ -123,21 +129,30 @@ private static Options configureOptions() {
...
-          Arrays.stream(mavenCoordinatesOption)
-              .map(DefaultArtifact::new)
-              .collect(toImmutableList());
+      return Arrays.stream(mavenCoordinatesOption)
+          .map(DefaultArtifact::new)
+          .collect(toImmutableList());
+    }
+  }
+
+  static ImmutableList<Path> generateInputClasspath(CommandLine commandLine)
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: Similarly here: You're not generating it.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 15]
```diff
@@ -49,33 +49,43 @@
...
     ClassDumper dumper = ClassDumper.create(jarPaths);
-    return new ClasspathChecker(onlyReachable, dumper, entryPoints);
-  }
 
-  /**
-   * If true, the report excludes linkage errors on classes that are not reachable
-   * from the entry points of the class usage graph.
-   */
-  private final boolean reportOnlyReachable;
+    ImmutableMap.Builder<Path, SymbolReferenceSet> jarToSymbolBuilder = ImmutableMap.builder();
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Check out `Maps.toMap(jarPaths, ClassDumper::scanSymbolReferencesInJar)`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 16]
```diff
@@ -49,33 +49,43 @@
...
+
+    return new ClasspathChecker(dumper, jarToSymbols, classReferenceGraph);
+  }
 
   private final ClassDumper classDumper;
 
-  private final ImmutableSet<Path> entryPoints;
-  
+  private final ImmutableMap<Path, SymbolReferenceSet> jarToSymbols;
+
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: You don't really need these blank lines in between simple field declarations, do you? Up to you.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 17]
```diff
@@ -49,33 +49,43 @@
...
-      boolean reportOnlyReachable,
       ClassDumper classDumper,
-      Iterable<Path> entryPoints) {
-    this.reportOnlyReachable = reportOnlyReachable;
+      Map<Path, SymbolReferenceSet> jarToSymbols,
+      ClassReferenceGraph classReferenceGraph) {
     this.classDumper = Preconditions.checkNotNull(classDumper);
-    this.entryPoints = ImmutableSet.copyOf(entryPoints);
+    this.jarToSymbols = ImmutableMap.copyOf(jarToSymbols);
+    this.classReferenceGraph = classReferenceGraph;
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]:
```suggestion
    this.classReferenceGraph = checkNotNull(classReferenceGraph);
```

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java [hunk 18]
```diff
@@ -131,6 +131,13 @@ public String formatByGroup() {
               .collect(Collectors.joining(", "));
 
       builder.append("Referenced by: ");
+
+      // A group (LinkageErrorCause) is marked unreachable if none of the errors in it is reachable
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]: Let's not change the dashboard report in this PR. I'm still not convinced this is something we should do.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 19]
```diff
@@ -92,54 +102,49 @@ public static void main(String[] arguments)
 
     CommandLine commandLine = ClasspathCheckOption.readCommandLine(arguments);
     ImmutableList<Path> inputClasspath = ClasspathCheckOption.generateInputClasspath(commandLine);
-    // TODO(suztomo): take command-line option to choose entry point classes for reachability
-    ImmutableSet<Path> entryPoints = ImmutableSet.of(inputClasspath.get(0));
 
-    boolean onlyReachable = commandLine.hasOption("r");
-    ClasspathChecker classpathChecker = create(onlyReachable, inputClasspath, entryPoints);
+    ImmutableSet.Builder<Path> entryPoints = ImmutableSet.builder();
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: I feel like `ClassPathCheckOption` should do this work to determine the entry points.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 20]
```diff
@@ -92,54 +102,49 @@ public static void main(String[] arguments)
...
-    for (Path jarPath : jarPaths) {
-      jarToSymbols.put(jarPath, ClassDumper.scanSymbolReferencesInJar(jarPath));
-    }
-
+  /** Finds linkage errors in the input classpath and generates a classpath check report. */
+  public ClasspathCheckReport findLinkageErrors() {
     // Validate linkage error of each reference
     ImmutableList.Builder<JarLinkageReport> jarLinkageReports = ImmutableList.builder();
-    for (Map.Entry<Path, SymbolReferenceSet> entry : jarToSymbols.build().entrySet()) {
+    for (Map.Entry<Path, SymbolReferenceSet> entry : jarToSymbols.entrySet()) {
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Consider using `Map.forEach`. It lets you avoid the whole `entry.getKey()`/`entry.getValue()` noise.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java [hunk 21]
```diff
@@ -44,6 +44,8 @@
   /** Returns the reason why the symbol reference is marked as a linkage error. */
   abstract Reason getReason();
 
+  abstract boolean isSourceClassReachable();
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java]: I think `isReachable` is enough here. No need for SourceClass. 
This does need JavaDoc.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java [hunk 22]
```diff
@@ -131,6 +131,12 @@ public String formatByGroup() {
               .collect(Collectors.joining(", "));
 
       builder.append("Referenced by: ");
+
+      String reachable =
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]:
```java
if (allErrorsForKey.stream().noneMatch(StaticLinkageError::isSourceClassReachable)) {
  builder.append("(unreachable)");
}
```

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java [hunk 23]
```diff
@@ -115,6 +127,8 @@ public String toString() {
 
     abstract StaticLinkageError.Builder<T> setReference(T reference);
 
+    abstract StaticLinkageError.Builder<T> setSourceClassReachable(boolean reachable);
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java]: setReachable

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java [hunk 24]
```diff
@@ -131,6 +131,12 @@ public String formatByGroup() {
...
+          allErrorsForKey.stream().anyMatch(StaticLinkageError::isSourceClassReachable)
+              ? "" // nothing if it's reachable
+              : "(unreachable)";
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]: Should you add a space afterwards?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java (hunk 21 above)
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java]: Javadoc, please.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java [hunk 25]
```diff
@@ -43,7 +43,7 @@
 import org.junit.Test;
 
 public class ClassDumperTest {
-  private static final String EXAMPLE_JAR_FILE =
+  static final String GRPC_CLOUD_FIRESTORE_JAR =
```
Comment (elharo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: can this be private?

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java [hunk 26]
```diff
@@ -0,0 +1,76 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.google.cloud.tools.opensource.classpath;
+
+import static com.google.cloud.tools.opensource.classpath.ClassDumperTest.GRPC_CLOUD_FIRESTORE_JAR;
```
Comment (elharo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java]: In general, it's probably better not to depend on test classes. Not a lot is saved by reusing this here.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java (hunk 10 above)
Comment (netdpb) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: Rather than making this nonprivate, and coupling your tests, I think you should copy it to the other test that needs it.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java [hunk 27]
```diff
@@ -0,0 +1,76 @@
...
+
+import com.google.common.collect.ImmutableSet;
+import com.google.common.truth.Truth;
+import java.io.IOException;
+import java.net.URISyntaxException;
+import org.junit.Test;
+
+public class ClassReferenceGraphTest {
+  private static ClassReferenceGraph createExampleGraph() throws URISyntaxException, IOException {
+    ClassSymbolReference grpcToA =
```
Comment (elharo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java]: one line

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java [hunk 28]
```diff
@@ -0,0 +1,76 @@
...
+ * distributed under the License is distributed on an "AS IS" BASIS,
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+package com.google.cloud.tools.opensource.classpath;
+
+import static com.google.cloud.tools.opensource.classpath.ClassDumperTest.EXAMPLE_JAR_FILE;
+import static com.google.cloud.tools.opensource.classpath.ClassDumperTest.absolutePathOfResource;
```
Comment (netdpb) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java]: Can you move this shared method somewhere outside of a test?

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckerTest.java [hunk 29]
```diff
@@ -85,8 +84,7 @@ public void testFindInvalidReferences_arrayCloneMethod() throws IOException, URI
   public void testFindInvalidReferences_constructorInAbstractClass()
       throws IOException, URISyntaxException {
     List<Path> paths = ImmutableList.of(absolutePathOfResource("testdata/guava-23.5-jre.jar"));
-    ClasspathChecker classpathChecker =
-        ClasspathChecker.create(false, paths, ImmutableSet.copyOf(paths));
+    ClasspathChecker classpathChecker = ClasspathChecker.create(paths, ImmutableSet.copyOf(paths));
```
Comment (netdpb) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckerTest.java]: If `ClasspathChecker.create()` took an `Iterable<Path>` as its second parameter, then the callers wouldn't all have to do the `ImmutableSet.copyOf()`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 12 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: This error is for developer (me), when this method is called without having BOM or Maven artifacts.

OptionGroup worked good for this case. Thanks.

> The option 'b' was specified but an option from this group has already been selected: 'a'

Nice message.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 13 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: Removed `Preconditions` in favor of the `else` clause.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 14 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: Fixed.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 15 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Hmm. `IOException` prevents it. 

image

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 16 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Removed.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 17 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Added.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 19 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: It makes sense. Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 20 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: That's cleaner. Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java (hunk 18 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]: Removed the mark from the dashboard.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java (hunk 22 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]: Removed the change.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java (hunk 24 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/JarLinkageReport.java]: Removed the change.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java (hunk 28 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java]: Created `TestHelper` class with this method.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java (hunk 27 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java]: Added an empty line.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckerTest.java (hunk 29 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckerTest.java]: Removed the unnecessary `copyOf`s

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java (hunk 21 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/StaticLinkageError.java]: Added

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java [hunk 30]
```diff
@@ -0,0 +1,107 @@
...
+import com.google.common.graph.MutableGraph;
+import java.io.IOException;
+import java.nio.file.Path;
+import java.util.ArrayDeque;
+import java.util.Queue;
+import java.util.Set;
+import org.apache.bcel.classfile.JavaClass;
+
+/**
+ * Directed graph of class references. Given classes in {@code entryPointJars}, it provides
```
[the remark this answers is not in the document]
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: Updated.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java (hunk 10 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: Copied.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java [hunk 31]
```diff
@@ -0,0 +1,122 @@
...
+import java.nio.file.Path;
+import java.util.ArrayDeque;
+import java.util.Collection;
+import java.util.Queue;
+import java.util.Set;
+import org.apache.bcel.classfile.JavaClass;
+
+/**
+ * Directed graph of class references. Given classes in a set of entry points, it provides {@link
+ * #isReachable(String)} for a class to check the reachability. The graph's node and edges are
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: This might be a good place to define reachability; either here or in README.md or both

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 5 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: This should be OK for now then

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 2 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: do you need to push this change?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 32]
```diff
@@ -91,55 +94,42 @@ public static void main(String[] arguments)
...
    */
   @VisibleForTesting
-  JarLinkageReport generateLinkageReport(Path jarPath, SymbolReferenceSet symbolReferenceSet) {
-    
+  JarLinkageReport generateLinkageReport(
+      Path jarPath, SymbolReferenceSet symbolReferenceSet) {
+
     JarLinkageReport.Builder reportBuilder = JarLinkageReport.builder().setJarPath(jarPath);
 
     // Because the Java compiler ensures that there are no static linkage errors between classes
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: static linkage --> linkage

File: dependencies/README.md [hunk 33]
```diff
@@ -72,7 +72,7 @@ and annotates linkage errors with [reachability](
...
 ../library-best-practices/glossary.md#entry-point-class).
 
-Entry point classes are different for the targets of checks:
-  - **Check for a BOM**: classes in the Maven artifacts listed in the BOM
-  - **Check for a project**: classes in the direct dependencies of the project
-  - **Check for a list of Maven artifacts**: classes in the Maven artifacts
+Entry point classes are different for the input of checks:
+  - **Check for a Maven BOM**: classes in the Maven artifacts listed in the BOM
+  - **Check for a list of Maven coordinates**: classes in the Maven artifacts
+  - **Check for a list of class and jar files**: classes in the list and the jar files
```
Comment (netdpb) [inline dependencies/README.md]: `all classes in the input are entry points. This means that every linkage error is considered reachable.`

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java (hunk 11 above)
Comment (netdpb) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: Interesting. There's a bug about optimizing that.

What about `ImmutableSet.copyOf(Traverser.forGraph(graph).breadthFirst(fromNodes))`.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java [hunk 34]
```diff
@@ -179,4 +180,21 @@ static void setRepositories(CommandLine commandLine) throws ParseException {
...
+  /** Returns a set of jar files that holds entry point classes. */
+  static ImmutableSet<Path> parseEntryPointJars(CommandLine commandLine, List<Path> inputClasspath)
+      throws RepositoryException {
+    ImmutableSet.Builder<Path> entryPoints = ImmutableSet.builder();
+    if (commandLine.hasOption("a") || commandLine.hasOption('b')) {
+      // For an artifact list (or a BOM), the first elements in inputClasspath are the artifacts
+      // specified the list, followed by their dependencies.
+      int artifactCount = generateArtifacts(commandLine).size();
+      // For Maven artifact list (or a BOM), entry point classes are ones in the list
+      entryPoints.addAll(inputClasspath.subList(0, artifactCount));
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: Just return `ImmutableSet.copyOf(inputClasspath.subList(0, artifactCount))` here, and return `ImmutableSet.copyOf(inputClassPath)` below on line 196. Then you don't need the builder at all.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 35]
```diff
@@ -101,21 +94,12 @@ public static void main(String[] arguments)
...
-      // For Maven artifact list (or a BOM), entry point classes are ones in the list
-      entryPoints.addAll(inputClasspath.subList(0, artifactCount));
-    } else {
-      // For list of jar files, entry point classes are all classes in the files
-      entryPoints.addAll(inputClasspath);
-    }
+    ImmutableList<Path> inputClasspath = ClasspathCheckOption.parseInputClasspath(commandLine);
+
+    ImmutableSet<Path> entryPointJars =
+        ClasspathCheckOption.parseEntryPointJars(commandLine, inputClasspath);
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: For later, it might be nice for `ClasspathCheckOption` to hold info about the command line in fields instead of having static methods. Then this method could look more like:

```java
Arguments arguments = Arguments.readCommandLine(arguments);
ClasspathChecker classpathChecker = create(arguments.inputClassPath(), arguments.entryPointJars());
```

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java [hunk 36]
```diff
@@ -125,10 +109,11 @@ public static void main(String[] arguments)
   public ClasspathCheckReport findLinkageErrors() {
     // Validate linkage error of each reference
     ImmutableList.Builder<JarLinkageReport> jarLinkageReports = ImmutableList.builder();
-    for (Map.Entry<Path, SymbolReferenceSet> entry : jarToSymbols.entrySet()) {
-      Path jarPath = entry.getKey();
-      jarLinkageReports.add(generateLinkageReport(jarPath, entry.getValue()));
-    }
+
+    jarToSymbols.forEach(
+        (jar, symbolReferenceSet) -> {
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: I think you can use an expression lambda here. (Remove the braces and the semicolon.)

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java (hunk 27 above)
Comment (netdpb) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraphTest.java]: I'm not sure why we need the empty line. And if google-java-format formats it this way, we should accept that.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/TestHelper.java [hunk 37]
```diff
@@ -0,0 +1,31 @@
...
+
+package com.google.cloud.tools.opensource.classpath;
+
+import java.net.URISyntaxException;
+import java.net.URLClassLoader;
+import java.nio.file.Path;
+import java.nio.file.Paths;
+
+/** Utility used among tests. */
+class TestHelper {
```
Comment (netdpb) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/TestHelper.java]: Add a private constructor to prevent instantiations.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java (hunk 31 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: I would let README.md define the term and adding `@see` link from this to the doc.

File: dependencies/README.md (hunk 33 above)
Comment (suztomo) [reply dependencies/README.md]: Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java (hunk 11 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: Great. Updated.
(I think `Graphs.reachableNodes` should be implemented in that way)

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 2 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: Thanks. (Somehow it was reverted) Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java (hunk 34 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathCheckOption.java]: Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 35 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Created an issue #419

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 36 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Removed braces.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/TestHelper.java (hunk 37 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/TestHelper.java]: Added.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java (hunk 32 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClasspathChecker.java]: Fixed.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java [hunk 38]
```diff
@@ -0,0 +1,99 @@
...
+import java.io.IOException;
+import java.nio.file.Path;
+import java.util.Collection;
+import java.util.Set;
+import org.apache.bcel.classfile.JavaClass;
+
+/**
+ * Directed graph of class references. Given classes in a set of entry points, it provides {@link
+ * #isReachable(String)} for a class to check whether the class is reachable from the entry point
+ * classes (reachability). The graph's nodes and edges are defined as following:
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: following --> follows

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassReferenceGraph.java]: Fixed
