### PR TITLE
No tools.jar in testFindLinkageProblems_unusedClassReferenceInByteCode

### LINKED ISSUE #1823: LinkageCheckerTest.testFindLinkageProblems_unusedClassReferenceInByteCode fails in Java 11
```
suztomo-macbookpro44% which java
/Library/Java/JavaVirtualMachines/jdk-11-latest/Contents/Home/bin/java
suztomo-macbookpro44% pwd        
/Users/suztomo/cloud-opensource-java/dependencies
suztomo-macbookpro44% mvn test -Dtest=LinkageCheckerTest#testFindLinkageProblems_unusedClassReferenceInByteCode
...

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.256 s <<< FAILURE! - in com.google.cloud.tools.opensource.classpath.LinkageCheckerTest
[ERROR] testFindLinkageProblems_unusedClassReferenceInByteCode(com.google.cloud.tools.opensource.classpath.LinkageCheckerTest)  Time elapsed: 0.166 s  <<< ERROR!
java.lang.IllegalArgumentException: Some jar files are not readable: [/Library/Java/JavaVirtualMachines/jdk-11.0.4.jdk/Contents/Home/../lib/tools.jar]
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerTest.testFindLinkageProblems_unusedClassReferenceInByteCode(LinkageCheckerTest.java:1167)

```

With Java 8:

```
suztomo-macbookpro44% echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-8-latest/Contents/Home
suztomo-macbookpro44% ls $JAVA_HOME/lib/tools.jar
/Library/Java/JavaVirtualMachines/jdk-8-latest/Contents/Home/lib/tools.jar
```

With Java 11:

```
suztomo-macbookpro44% ls $JAVA_HOME/lib/tools.jar
ls: /Library/Java/JavaVirtualMachines/jdk-11-latest/Contents/Home/lib/tools.jar: No such file or directory
```

# What is the test looking for?

```

  @Test
  public void testFindLinkageProblems_unusedClassReferenceInByteCode() throws IOException {
    // JDK's tools.jar contains com.sun.tools.internal.ws.wscompile.WsgenOptions class. The class
    // has the class reference to JDK's com.sun.xml.internal.ws.api.BindingID$SOAPHTTPImpl in its
    // constant pool section. The referenced class is private but it's not used in the JVM
    // instructions in the class file.
    // https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1608

    String javaHomeDirectory = System.getProperty("java.home");
    Path toolsJar = Paths.get(javaHomeDirectory, "..", "lib", "tools.jar");
    Artifact toolsArtifact =
        new DefaultArtifact("com.sun:tools:jar:1.8").setFile(toolsJar.toFile());

    LinkageChecker linkageChecker =
        LinkageChecker.create(ImmutableList.of(new ClassPathEntry(toolsArtifact)));
    ImmutableSet<LinkageProblem> linkageProblems = linkageChecker.findLinkageProblems();

    Truth.assertThat(linkageProblems).isEmpty();
  }
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1823 

tools.jar does not exist in Java 11. The test should not rely on the jar file.

The two classes `com.sun.tools.ws.wscompile.WsgenOptions` and `com.sun.xml.ws.api.BindingID$SOAPHTTPImpl` the test needed from the tools.jar are available in `com.sun.xml.ws:jaxws-tools:2.3.3` and `com.sun.xml.ws:jaxws-rt:2.3.3`.

### CODE REVIEW

**Review by elharo — COMMENTED** [review]
Can you add a fixes line to the description so it will autoclose the right bug? Thanks.

**Comment by suztomo** [comment]
Added the issue number for auto-closing the issue.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java [hunk 1]
```diff
@@ -1152,22 +1151,39 @@ public void testFindLinkageProblems_referenceToJava11Method() throws IOException
...
+            "com.sun.xml.ws:jaxws-rt:2.3.3"); // This contains BindingID$SOAPHTTPImpl
+    String wsgenOptionsClassName = "com.sun.tools.ws.wscompile.WsgenOptions";
+
+    // Ensure the class path contains the two classes in the issue (#1608).
+    ClassDumper classDumper = ClassDumper.create(classPath);
+    SymbolReferences symbolReferences = classDumper.findSymbolReferences();
+    ImmutableSet<ClassSymbol> classSymbols =
+        symbolReferences.getClassSymbols(new ClassFile(classPath.get(0), wsgenOptionsClassName));
+    Truth.assertThat(classSymbols)
+        .contains(new ClassSymbol("com.sun.xml.ws.api.BindingID$SOAPHTTPImpl"));
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java:1174]: This class is a private class.

**Review by elharo — APPROVED** [review]
