### PR TITLE
Not to load shadowed class file in a class path

### LINKED ISSUE #495: LinkageChecker unable to check  io.grpc:grpc-alts:jar:1.18.0 com.google.cloud:google-cloud-nio:jar:0.81.0-alpha
There seems a bug:

argument
```
-a io.grpc:grpc-alts:jar:1.18.0,com.google.cloud:google-cloud-nio:jar:0.81.0-alpha
```

```
Exception in thread "main" com.google.common.base.VerifyException: The target class symbol reference org.apache.http.client.config.RequestConfig$Builder is not found in source class com.google.api.client.http.apache.ApacheHttpRequest
	at com.google.common.base.Verify.verify(Verify.java:124)
	at com.google.cloud.tools.opensource.classpath.ClassDumper.isUnusedClassSymbolReference(ClassDumper.java:585)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.checkLinkageErrorMissingClassAt(LinkageChecker.java:340)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.errorsFromSymbolReferences(LinkageChecker.java:141)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.generateLinkageReport(LinkageChecker.java:110)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.lambda$findLinkageErrors$0(LinkageChecker.java:86)
	at com.google.common.collect.RegularImmutableMap.forEach(RegularImmutableMap.java:186)
	at com.google.cloud.tools.opensource.classpath.LinkageChecker.findLinkageErrors(LinkageChecker.java:84)
	at com.google.cloud.tools.opensource.classpath.LinkageCheckerMain.main(LinkageCheckerMain.java:51)

```

The class com.google.api.client.http.apache.ApacheHttpRequest exists in multiple jar files in the class path:

```
/usr/local/google/home/suztomo/.m2/repository/com/google/http-client/google-http-client/1.19.0/google-http-client-1.19.0.jar contains com.google.api.client.http.apache.ApacheHttpRequest
/usr/local/google/home/suztomo/.m2/repository/com/google/http-client/google-http-client-apache/2.0.0/google-http-client-apache-2.0.0.jar contains com.google.api.client.http.apache.ApacheHttpRequest
```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #495 , a bug where LinkageChecker was not able to handle duplicated class files in a class path correctly. [A test case](https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/496/files#diff-40dc800f7109446f3727fe9ff7f3a937R822) is also added.

# Detail of the issue

In this case of #495, `com.google.api.client.http.apache.ApacheHttpRequest` in `google-http-client-apache-2.0.0.jar` was checked for its reference. LinkageChecker failed because the class is shadowed by the one in `google-http-client-1.19.0.jar`. Because the former class file is shadowed, it's never used in the class path. No need to check its references.

This fix is not to load a class file shadowed by another class file. This is achieved by using one shared class path (ClassDumper's instance variable `classRepository`) to read jar files for `JavaClass`es.

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 1]
```diff
@@ -151,13 +151,12 @@ boolean isSystemClass(String className) {
...
    */
-  static SymbolReferenceSet scanSymbolReferencesInJar(Path jarFilePath)
-      throws IOException {
+  SymbolReferenceSet scanSymbolReferencesInJar(Path jarFilePath) throws IOException {
     checkArgument(jarFilePath.isAbsolute(), "The input jar file path is not an absolute path");
     checkArgument(Files.isReadable(jarFilePath), "The input jar file path is not readable");
 
     SymbolReferenceSet.Builder symbolTableBuilder = SymbolReferenceSet.builder();
-    for (JavaClass javaClass : listClassesInJar(jarFilePath)) {
+    for (JavaClass javaClass : listClassesInJarFromClassPath(jarFilePath)) {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Because `listClassesInJarFromClassPath` uses instance variable `classRepository`, these methods are now non-static method.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 2]
```diff
@@ -151,13 +151,12 @@ boolean isSystemClass(String className) {
    *
    * @param jarFilePath absolute path to a jar file
    */
-  static SymbolReferenceSet scanSymbolReferencesInJar(Path jarFilePath)
-      throws IOException {
+  SymbolReferenceSet scanSymbolReferencesInJar(Path jarFilePath) throws IOException {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: argument could simply be jar or maybe jarPath. jarFilePath is redundant.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 3]
```diff
@@ -415,6 +415,19 @@ Path findClassLocation(String className) {
     return javaClasses.build();
   }
 
+  /** Returns a set of {@link JavaClass}es in {@code jarPath}. */
+  static ImmutableSet<JavaClass> listClassesInJar(Path jarPath) throws IOException {
+    return listClassesInJar(jarPath, createClassRepository(ImmutableList.of(jarPath)));
+  }
+
+  /**
+   * Returns a set of {@link JavaClass}es in {@code jarPath} via the class path in {@link
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: From this comment I don't understand the difference between this method and the previous one. Can you elaborate and clarify?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 4]
```diff
@@ -584,7 +597,10 @@ boolean isUnusedClassSymbolReference(ClassSymbolReference reference) {
           constantPoolIndexForClass(sourceJavaClass, targetClassName);
       Verify.verify(
           !targetConstantPoolIndices.isEmpty(),
-          "The target class symbol reference is not found in source class");
+          "The target class symbol reference "
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: delete "symbol reference" here. It's understood.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 3 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Added comparison.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 4 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Updated

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 3 above)
Comment (netdpb) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: I agree. Should at least the one that takes a `Repository` become an instance method on `Repository`? Then you don't really need the next one at all.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 5]
```diff
@@ -584,7 +604,10 @@ boolean isUnusedClassSymbolReference(ClassSymbolReference reference) {
           constantPoolIndexForClass(sourceJavaClass, targetClassName);
       Verify.verify(
           !targetConstantPoolIndices.isEmpty(),
-          "The target class symbol reference is not found in source class");
+          "The target class "
+              + targetClassName
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: `Verify.verify` is varargs and uses a simple format.

```java
verify(
    !targetConstantPoolIndices.isEmpty(),
    "The target class %s is not found in source class %s",
    targetClassName,
    sourceJavaClass.getClassName());
```

The above is easier to read and can be more performant (which doesn't matter in this case) because string formatting doesn't happen unless verification fails.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java [hunk 6]
```diff
@@ -345,7 +347,9 @@ public void testIsUnusedClassSymbolReference_classSymbolReferenceNotFound()
     } catch (VerifyException ex) {
       // pass
       Truth.assertThat(ex.getMessage())
```
Comment (netdpb) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: `Truth.assertThat(ex).hasMessageThat().isEqualTo(...);`

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 5 above)
Comment (elharo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: I disagree that format strings are easier to read than simple string concatenation. I like my words to come in the order I read them. Missing and out of order format string arguments are a common source of bugs. 

And to performance, I say [Knuth](http://wiki.c2.com/?PrematureOptimization)!

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java (hunk 6 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 5 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: I agree that string concatenation is just fine compared to adding `String.format()`.

For this case, I would use the varargs is for `verify()`; I like calling functions the way the implementation intends to.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 1 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Right. That design works well.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 3 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: The private one that takes a Repository is to have the common logic between the other two. Because one of them is `static` (no need to be as an instance method), the private one is static.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: As discussed, the two static methods were not needed, as the caller only needed class names. Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 7]
```diff
@@ -371,45 +374,47 @@ Path findClassLocation(String className) {
...
+        .collect(toImmutableSet());
   }
 
-  static ImmutableSet<JavaClass> listClassesInJar(Path jarPath) throws IOException {
-    Repository repository = createClassRepository(ImmutableList.of(jarPath));
+  /**
+   * Returns a set of {@link JavaClass}es which has entries in the {@code jar} through {@link
+   * #classRepository}.
+   */
+  private ImmutableSet<JavaClass> listClassesInJar(Path jar) throws IOException {
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Now other 2 static methods are removed.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java [hunk 8]
```diff
@@ -100,11 +100,11 @@ public void testListInnerClasses() throws IOException {
   }
 
   @Test
-  public void testCreationInvalidInput() {
+  public void testCreationInvalidInput() throws IOException {
     try {
       ClassDumper.create(ImmutableList.of(Paths.get("")));
       Assert.fail("Empty path should generate IOException");
-    } catch (IOException ex) {
+    } catch (IllegalArgumentException ex) {
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: Previously it was throwing IOException when ClassRepository was trying to read file with empty string. Now it has checkArgument validation against such case.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 9]
```diff
@@ -371,45 +373,47 @@ Path findClassLocation(String className) {
...
-    return classPath.getAllClasses();
+    return classPath.getAllClasses().stream()
+        .map(ClassInfo::getName)
+        .collect(toImmutableSet());
   }
 
-  static ImmutableSet<JavaClass> listClassesInJar(Path jarPath) throws IOException {
-    Repository repository = createClassRepository(ImmutableList.of(jarPath));
+  /**
+   * Returns a set of {@link JavaClass}es which has entries in the {@code jar} through {@link
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: has --> have

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 10]
```diff
@@ -584,7 +588,9 @@ boolean isUnusedClassSymbolReference(ClassSymbolReference reference) {
           constantPoolIndexForClass(sourceJavaClass, targetClassName);
       Verify.verify(
           !targetConstantPoolIndices.isEmpty(),
-          "The target class symbol reference is not found in source class");
+          "The target class %s is not found in source class %s",
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: This message doesn't sound right unless target class is an inner class.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 9 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Fixed

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 10 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Updated.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 11]
```diff
@@ -584,7 +588,9 @@ boolean isUnusedClassSymbolReference(ClassSymbolReference reference) {
           constantPoolIndexForClass(sourceJavaClass, targetClassName);
       Verify.verify(
           !targetConstantPoolIndices.isEmpty(),
-          "The target class symbol reference is not found in source class");
+          "The reference to the target class %s is not found in the source class %s",
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Is this accurate? The source class is missing a reference? I'd expect something like

Source class A references target class B, but B could not be found. 

This is more like 

Target class B could be found but source class A does not have a reference to target class B.

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Clarified the message. This `verify` is asserting "This should not happen".

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java [hunk 12]
```diff
@@ -817,4 +817,23 @@ public void testFindLinkageErrors_doesNotCatchNoClassDefFoundError()
...
+    List<Path> paths =
+        ClassPathBuilder.artifactsToClasspath(
+            ImmutableList.of(
+                new DefaultArtifact("io.grpc:grpc-alts:jar:1.18.0"),
+                new DefaultArtifact("com.google.cloud:google-cloud-nio:jar:0.81.0-alpha")));
+
+    LinkageChecker linkageChecker = LinkageChecker.create(paths, paths);
+
+    // This should not raise an exception
+    linkageChecker.findLinkageErrors();
```
Comment (elharo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java]: What's the return value here? Should this report an error, though not throw an exception?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 13]
```diff
@@ -86,23 +87,26 @@ private static Repository createClassRepository(List<Path> paths) {
   static ClassDumper create(List<Path> jarPaths) throws IOException {
     ClassLoader systemClassLoader = ClassLoader.getSystemClassLoader();
     ClassLoader extensionClassLoader = systemClassLoader.getParent();
+    jarPaths.forEach(
+        jar -> {
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Looks like this PR needs to be updated to current master.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java (hunk 12 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java]: Updated the line to clarify the return value. The return value is a valid `LinkageCheckReport` instance.
(Duplicate class files in class path do not mean a linkage error.)

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 13 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Merged.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 14]
```diff
@@ -371,45 +373,47 @@ Path findClassLocation(String className) {
...
         com.google.common.reflect.ClassPath.from(classLoaderFromJar);
 
-    return classPath.getAllClasses();
+    return classPath.getAllClasses().stream()
+        .map(ClassInfo::getName)
+        .collect(toImmutableSet());
   }
 
-  static ImmutableSet<JavaClass> listClassesInJar(Path jarPath) throws IOException {
-    Repository repository = createClassRepository(ImmutableList.of(jarPath));
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: This (creating a `Repository` with a new class path that has only this jar file) was the cause of the bug. When listing `JavaClass`, it was not using the class path passed to `ClassDumper` constructor.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 15]
```diff
@@ -86,23 +87,26 @@ private static Repository createClassRepository(List<Path> paths) {
   static ClassDumper create(List<Path> jarPaths) throws IOException {
     ClassLoader systemClassLoader = ClassLoader.getSystemClassLoader();
     ClassLoader extensionClassLoader = systemClassLoader.getParent();
+    jarPaths.forEach(
+        jar -> {
+          checkArgument(Files.isRegularFile(jar), "The jar file is not a regular file: %s", jar);
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Previously, when an invalid input was given, it was caught at this function. But it's no longer the case.
https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/496/files#diff-6e13c859770f686d992e68ec76956e75R103
Without `checkArgument`, `ClassDumper.create()` would succeed even with invalid input.

**Comment by suztomo** [comment]
@elharo PTAL.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 16]
```diff
@@ -376,65 +379,46 @@ Path findClassLocation(String className) {
   static ImmutableMap<String, Path> mapClassToJar(List<Path> jars) throws IOException {
```
Comment (netdpb) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: You could implement this method based on `mapJarToClasses` and avoid some code duplication:

```java
return ImmutableMap.copyOf(
    Maps.transformValues(
        Multimaps.asMap(mapJarToClasses(jars).inverse()), jars -> Iterables.get(jars, 0)));
```

But I have a question: Why is it important to know the _first_ jar that contains a given class, and not the rest? How is this method used?

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Updated. That's nice to report invalid inputs at once.
