### PR TITLE
Linkage Checker to handle classifier in artifacts

### LINKED ISSUE #2173: Linkage Checker to work with artifacts with classifiers
Linkage Checker to work with artifacts with classifiers

https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/2162#discussion_r680151651

Given build.gradle:

```
plugins {
    id 'java'
    id 'com.google.cloud.tools.linkagechecker' version "1.5.9"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compile 'com.google.cloud:google-cloud-core:1.95.4'
    compile 'com.google.cloud:google-cloud-core:1.95.4:tests'
}

test {
    useJUnitPlatform()
}

linkageChecker {
    configurations = ['compile']
}
```

Running the command below fails:

```
./gradlew linkageCheck --stacktrace
...
* What went wrong:
Execution failed for task ':linkageCheck'.
> com.google.cloud:google-cloud-core:1.95.4 is not in the class path
...
Caused by: java.lang.IllegalArgumentException: com.google.cloud:google-cloud-core:1.95.4 is not in the class path
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:219)
        at com.google.cloud.tools.opensource.classpath.ClassPathResult.formatDependencyPaths(ClassPathResult.java:68)
        at com.google.cloud.tools.opensource.classpath.LinkageProblem.dependencyPathsOfProblematicJars(LinkageProblem.java:248)
        at com.google.cloud.tools.opensource.classpath.LinkageProblem.formatLinkageProblems(LinkageProblem.java:228)
        at com.google.cloud.tools.dependencies.gradle.LinkageCheckTask.findLinkageErrors(LinkageCheckTask.java:159)
        at com.google.cloud.tools.dependencies.gradle.LinkageCheckTask.run(LinkageCheckTask.java:98)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)

```

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #2173

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/MavenDependencyMediation.java [hunk 1]
```diff
@@ -44,7 +46,7 @@ public AnnotatedClassPath mediate(DependencyGraph dependencyGraph) {
 
       File file = artifact.getFile();
       if (file != null && file.getName().endsWith(".jar")) {
-        String versionlessCoordinates = Artifacts.makeKey(artifact);
+        String versionlessCoordinates = Artifacts.makeKey(artifact) + artifact.getClassifier();
```
Comment (elefeint) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/MavenDependencyMediation.java:49]: Does `getClassifier()` return the colon prefix, too? Like ":test"?

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java [hunk 2]
```diff
@@ -1285,4 +1286,36 @@ public void testBomResolutionWithMissingTransitiveDependency() throws Exception
...
+
+  @Test
+  public void testBomHavingClassifierArtifacts() throws Exception {
+    String pomFile = "bom-with-classifier-artifacts.pom";
+    Bom bom = Bom.readBom(TestHelper.absolutePathOfResource(pomFile));
+
+    LinkageChecker linkageChecker = LinkageChecker.create(bom);
+    ImmutableSet<LinkageProblem> linkageProblems = linkageChecker.findLinkageProblems();
+
+    // bom-with-classifier-artifacts contains com.google.cloud:goole-cloud-core:jar:tests:1.96.0.
```
Comment (dzou) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java:1298]:
```suggestion
    // bom-with-classifier-artifacts contains com.google.cloud:google-cloud-core:jar:tests:1.96.0.
```

**Review by elefeint — APPROVED** [review]

File: gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java [hunk 3]
```diff
@@ -307,14 +309,20 @@ private static DependencyGraph createDependencyGraph(ResolvedConfiguration confi
...
+      for (ResolvedArtifact artifact : node.getModuleArtifacts()) {
+        // parentPath is null for the first item
+        path =
+            parentPath == null
+                ? new DependencyPath(artifactFrom(node, artifact))
+                : parentPath.append(dependencyFrom(node, artifact));
+        graph.addPath(path);
+      }
 
+      Verify.verify(
```
Comment (dzou) [inline gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java:324]: Is `path != null` equivalent to `!node.getModuleArtifacts().isEmpty()`? If so you may be able to just verify that condition instead which would allow you to avoid defining `path` outside the loop.

**Review by dzou — COMMENTED** [review]
LGTM on my end, will let Elena a chance to review

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/MavenDependencyMediation.java (hunk 1 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/MavenDependencyMediation.java:49]: No, it doesn't give a colon prefix. Let me add one. I think it's more clear.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java (hunk 2 above)
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerTest.java]: Done.

File: gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java (hunk 3 above)
Comment (suztomo) [reply gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java]: Updated this to check more earlier.

File: gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java [hunk 4]
```diff
@@ -285,7 +283,7 @@ private static Dependency dependencyFrom(
     return new Dependency(artifact, "compile");
   }
 
-  private static DependencyGraph createDependencyGraph(ResolvedConfiguration configuration) {
```
Comment (suztomo) [inline gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java:286]: Removing static because it now accesses getLogger.

File: gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java [hunk 5]
```diff
@@ -333,7 +337,7 @@ private static DependencyGraph createDependencyGraph(ResolvedConfiguration confi
     return graph;
   }
 
-  private static ClassPathResult createClassPathResult(ResolvedConfiguration configuration) {
```
Comment (suztomo) [inline gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java:328]: Removing static because it accesses createDependencyGraph, which is now non-static.

**Review by elefeint — APPROVED** [review]

File: gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java [hunk 6]
```diff
@@ -307,13 +307,25 @@ private static DependencyGraph createDependencyGraph(ResolvedConfiguration confi
 
       DependencyPath parentPath = item.getParentPath();
 
-      // parentPath is null for the first item
-      DependencyPath path =
-          parentPath == null
-              ? new DependencyPath(artifactFrom(node))
-              : parentPath.append(dependencyFrom(node));
+      DependencyPath path = null;
```
Comment (dzou) [inline gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java:310]: Just reminder to define this in the loop if it is no longer needed outside.

**Review by dzou — APPROVED** [review]

File: gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java (hunk 6 above)
Comment (suztomo) [reply gradle-plugin/src/main/java/com/google/cloud/tools/dependencies/gradle/LinkageCheckTask.java:310]: This variable is needed outside.
