### PR TITLE
LinkageCheckerMain to throw LinkageCheckResultException when it finds error

### LINKED ISSUE #1348: LinkageCheckerMain to exit non-zero status when it finds linkage errors
LinkageCheckerMain to exit non-zero status.

I tried [Linkage Checker with Gradle](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/Linkage-Checker-with-Gradle), but the build unexpectedly succeeded even with the presence of linkage errors.

https://github.com/googleapis/gax-java/pull/1019

```
...
(io.grpc:grpc-context:1.22.1) io.grpc.Deadline's method after(long arg1, java.util.concurrent.TimeUnit arg3, io.grpc.Deadline$Ticker arg4) is not accessible;
  referenced by 1 class file
    io.grpc.internal.ServerImpl (io.grpc:grpc-core:1.28.1)

io.grpc:grpc-netty-shaded:1.28.1 is at:
  com.google.api:gax-grpc:1.56.0 (compile) / io.grpc:grpc-netty-shaded:1.28.1 (compile)
  and 1 dependency path.
io.grpc:grpc-context:1.22.1 is at:
  com.google.api:gax-grpc:1.56.0 (compile) / com.google.api:gax:1.56.0 (compile) / io.opencensus:opencensus-api:0.24.0 (compile) / io.grpc:grpc-context:1.22.1 (compile)
  and 8 other dependency paths.
io.grpc:grpc-core:1.28.1 is at:
  com.google.api:gax-grpc:1.56.0 (compile) / io.grpc:grpc-netty-shaded:1.28.1 (compile) / io.grpc:grpc-core:1.28.1 (compile)
  and 3 other dependency paths.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 29s
37 actionable tasks: 24 executed, 13 up-to-date
...

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1348 

Status code (success/failure) logic:

```
if "--output-exclusion-file" is specified:
  writes linkage errors to file
  exits with success
else
  if linkage errors are found:
    print linkage error
    exits with failure
  else
    exits with success
```

I confirmed Gradle can detect non-zero exit code upon an exception: https://gist.github.com/suztomo/9ddfae0ec141042ca6ba9b0434b6de54

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMain.java [hunk 1]
```diff
@@ -98,12 +99,15 @@ public static void main(String[] arguments)
...
         Path writeAsExclusionFile = linkageCheckerArguments.getOutputExclusionFile();
         if (writeAsExclusionFile != null) {
           ExclusionFiles.write(writeAsExclusionFile, symbolProblems);
           System.out.println("Wrote the linkage errors as exclusion file: " + writeAsExclusionFile);
+          return;
+        }
+
+        if (!symbolProblems.isEmpty()) {
+          System.out.println(SymbolProblem.formatSymbolProblems(symbolProblems));
         }
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMain.java:111]: I know think with "--output-exclusion-file" option the tool should not print linkage errors. Showing "Wrote the linkage errors as exclusion file: ..." message is the exact effect of the option. Showing other linkage errors in console, potentially hundreds of lines, obscures the message.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java [hunk 2]
```diff
@@ -64,8 +67,12 @@ public void testJarFiles()
 
     String jarArgument = googleCloudCore + "," + googleCloudFirestore + "," + guava;
 
-    // This should not raise Exception
-    LinkageCheckerMain.main(new String[] {"-j", jarArgument});
+    try {
+      LinkageCheckerMain.main(new String[] {"-j", jarArgument});
+      fail("LinkageCheckerMain should throw LinkageCheckResultException upon errors");
+    } catch (LinkageCheckResultException expected) {
```
Comment (suztomo) [inline dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java:73]: With `System.exit`, we would not be able to test LinkageCheckerMain's failure status. Therefore this PR proposes an exception to tell the failure to the caller of the tool (Gradle in mind).

**Comment by suztomo** [comment]
Windows build failed:

```
[ERROR]   LinkageCheckerMainIntegrationTest.testWriteLinkageErrorsAsExclusionFile:172 expected:<...7141845838425412.xml[]
> but was:<...7141845838425412.xml[
]
```

**Comment by suztomo** [comment]
Fixed Windows build.

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java (hunk 2 above)
Comment (elharo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/LinkageCheckerMainIntegrationTest.java:73]: You could extract everything from main except System.exit() into a new method and test that. Or you could add an extra "don't exit" argument for tests, or some such. But this should work too.
