### PR TITLE
Linkage Monitor to read artifact list file that contains Maven coordinates with versions

### LINKED ISSUE #1958: Linkage Monitor unexpectedly recognizes the root parent pom as a BOM
(This is a regression of #1920)

The problem in java-asset repository https://github.com/googleapis/java-asset/issues/570 was caused by Linkage Monitor unexpectedly recognizing the root pom.xml as a BOM and thus reading the dependencyManagement section to create a snapshot Libraries BOM.

We want to read the dependencyManagement section of BOMs to populate `LinkageMonitor.localArtifacts`, because gax-java repository has gax-bom to tell which artifacts are generated by the repository.

Note that google-cloud-bom is a BOM but `LinkageMonitor.localArtifacts` does not need to have its dependencyManagement section.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #1958 

Another approach for the problem. Compared with https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1961, this PR expects the artifact list file to have Maven coordinates with versions. In gax-java repository, Gradle's build.gradle will create such file.

# What is the file will look like?

```

com.google.api:gax:1.60.0-SNAPSHOT
com.google.api:gax-grpc:1.60.0-SNAPSHOT
com.google.api:gax-httpjson:1.60.0-SNAPSHOT
```

A simple Gradle task can generate this file using `$version`. In gax-java's build.gradle. I'll add

```
task createLinkageMonitorArtifactList {
  doLast {
    new File(projectDir, "linkage-monitor-artifacts.txt").text = """
com.google.api:gax:$version
com.google.api:gax-grpc:$version
com.google.api:gax-httpjson:$version
"""
  }
}
```

CC: @chingor13 who owns gax-java

### CODE REVIEW

File: linkage-monitor/src/main/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitor.java [hunk 1]
```diff
@@ -193,27 +203,60 @@ private static void printUsageAndDie() {
...
-        if ("pom".equals(model.getPackaging()) && dependencyManagement != null) {
-          // Read the content of a BOM.
-          for (org.apache.maven.model.Dependency dependency :
-              dependencyManagement.getDependencies()) {
-            String managedDependencyVersionlessCoordinates =
-                dependency.getGroupId() + ":" + dependency.getArtifactId();
-            artifactToVersion.put(managedDependencyVersionlessCoordinates, dependency.getVersion());
-            logger.fine("Found local artifact in the BOM: " + dependency);
-          }
-        }
```
Comment (suztomo) [inline linkage-monitor/src/main/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitor.java:206]: This reverts https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1920, which causes the problem of mixing BOMs and parent POMs.

**Review by elharo — APPROVED** [review]

**Comment by suztomo** [comment]
Confirmed it works with gax-java (I renamed ClientSettings to ClientSettingsFoo and Linkage Monitor detected it successfully)

https://gist.github.com/suztomo/79304de2a0953ffe12e8a37c4a0879bc
