### PR TITLE
ClassDumper. findClassLocation to check special class file name too

### LINKED ISSUE #837: Linkage Checker cannot find classes in WEB-INF/classes in a WAR
I was testing the enforcer rule with Ray's grpc Java example https://github.com/saturnism/grpc-java-by-example/tree/master/chat-example/chat-vaadin-client with excluding nonexistent vaadin-buildhelpers ([commit](https://github.com/suztomo/grpc-java-by-example/commit/97e7296ad3a72ea96ca7031d4bc8b2a029da70c0)). It failed with NullPointerException.

```
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull (Preconditions.java:878)
    at com.google.cloud.tools.opensource.classpath.ClassFile.<init> (ClassFile.java:34)
    at com.google.cloud.tools.opensource.classpath.ClassDumper.findSymbolReferences (ClassDumper.java:161)
    at com.google.cloud.tools.opensource.classpath.LinkageChecker.create (LinkageChecker.java:76)
    at com.google.cloud.tools.dependencies.enforcer.LinkageCheckerRule.execute (LinkageCheckerRule.java:170)
    at org.apache.maven.plugins.enforcer.EnforceMojo.execute (EnforceMojo.java:194)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

```

The failure is because `findClassLocation("AppWidgetset")` returns `null` somehow.

```
ClassFile source = new ClassFile(findClassLocation(className), className);
```

image

ClassLoader for WARs can fetch classes in `WEB-INF.classes` in a WAR. The returned JavaClass contains class name "AppWidgetset", but `ClassDumper`'s `classToJarFile` holds entry of `WEB-INF/classes/AppWidgetset`.

I remember our ClassPathRepository has classFileNames to resolve this situation.

```
  /**
   * Mapping from class names to special class file locations.
   *
   * <p>While class name and class file name are the same in most cases, sometimes classes are not
   * placed in the root of a JAR file to support a framework-specific JAR structure. For example,
   * Spring Boot Gradle Java plugin places class files under "BOOT-INF/classes". To load such
   * classes by class name, this mapping keeps track of the special location once they are loaded.
   *
   * <ul>
   *   <li>Key: class name (value from {@link JavaClass#getClassName()}) which has a special class
   *       file name different from its class name. Example: {@code com.google.Foo}
   *   <li>Value: the special class file name as in {@link JavaClass#getFileName()}, a path that
   *       locates a class file in a class path. Example: {@code BOOT-INF.classes.com.google.Foo}
   * </ul>
   *
   * @see <a
   *     href="https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html"
   *     >Spring Boot Reference Guide: The Executable Jar Format</a>
   */
  private final Map<String, String> classFileNames;
```

To investigate how we can leverage it to resolve this problem.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #837 .

ClassDumper.findClassLocation was not able to find JAR file if the class name and class file name are different. For example in #837, AppWidgetset  has class name "AppWidgetset" but class file name "WEB-INF.classes.AppWidgetset" with WAR-specific prefix.

This PR fixes such case, leveraging `FixedSizeClassPathRepository.classFileNames`.

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 1]
```diff
@@ -93,7 +92,7 @@ static ClassDumper create(List<Path> jarPaths) throws IOException {
     checkArgument(
         unreadableFiles.isEmpty(), "Some jar files are not readable: %s", unreadableFiles);
 
-    return new ClassDumper(jarPaths, extensionClassLoader, mapJarToClasses(jarPaths));
+    return new ClassDumper(jarPaths, extensionClassLoader, mapJarToClassFileNames(jarPaths));
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: These variable name change is to clarify whether its class name (such as `AppWidgetset`) or class file name (such as `WEB-INF.classes.AppWidgetset`).

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 2]
```diff
@@ -322,20 +321,32 @@ Path findClassLocation(String className) {
...
     // location of the target class, and sometimes the superclass is unavailable.
-    return Iterables.getFirst(classToJarFiles.get(className), null);
+    Path path = Iterables.getFirst(classFileNameToJarFiles.get(className), null);
+    if (path != null) {
+      return path;
+    }
+
+    // Some classes have framework-specific prefix such as "WEB-INF.classes.AppWidgetset" in its
+    // class file name.
+    String specialLocation = classRepository.getSpecialLocation(className);
```
Comment (suztomo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: This is the main change of this PR.
