### PR TITLE
ClassDumper to report problematic file name if any

### LINKED ISSUE #2080: ClassDumper should tell problematic file names upon ZipException
```
[ERROR] testForNewLinkageErrors(com.google.cloud.MaximumLinkageErrorsTest)  Time elapsed: 204.871 s  <<< ERROR!
java.util.zip.ZipException: error in opening zip file
	at com.google.cloud.MaximumLinkageErrorsTest.testForNewLinkageErrors(MaximumLinkageErrorsTest.java:52)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   MaximumLinkageErrorsTest.testForNewLinkageErrors:52 » Zip error in opening zip...
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Google Cloud Platform Supported Libraries 20.4.1-SNAPSHOT SUCCESS [  0.218 s]
[INFO] Google Cloud Long Term Support BOM 0.1.0-SNAPSHOT .. SUCCESS [  0.008 s]
[INFO] BOM Parent 1.0-SNAPSHOT ............................ SUCCESS [  0.006 s]
[INFO] Cloud Platform Supported Libraries Upper Bounds Check 2.0.0-SNAPSHOT SUCCESS [  1.799 s]
[INFO] integration-tests 1.2.0-SNAPSHOT ................... FAILURE [03:27 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:29 min
[INFO] Finished at: 2021-05-19T14:12:08-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project integration-tests: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/suztomo/cloud-opensource-java/boms/integration-tests/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :integration-tests
suztomo-macbookpro44% jar tf  ~/.m2/repository/xerces/xerces-impl/2.6.2/xerces-impl-2.6.2.jar
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:126)
	at sun.tools.jar.Main.list(Main.java:1115)
	at sun.tools.jar.Main.run(Main.java:293)
	at sun.tools.jar.Main.main(Main.java:1288)
suztomo-macbookpro44% cat ~/.m2/repository/xerces/xerces-impl/2.6.2/xerces-impl-2.6.2.jar
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-
transitional.dtd'><html><head><script type='text/javascript'>url='https://searchassist.verizon.com/main?
ParticipantID=euekiz39ksg8nwp7iqj2fp5wzfwi5q76&FailedURI=http%3A%2F%2Frepo2.maven.org%2Fmaven2%2Fxerces%2
Fxerces-impl%2F2.6.2%2Fxerces-impl-2.6.2.jar&FailureMode=1&Implementation=&AddInType=4&Version=jswr0.1&ClientLocation=uk
&JS=1';if(top.location!=location){var w=window,d=document,e=d.documentElement,b=d.body,x=w.innerWidth||e.clientWidth||b.clientWidth,y=w.innerHeight||e.clientHeight||b.clientHeight;url+='&w='+x+'&h='+y;}window.location.replace(url);</script></html>
suztomo-macbookpro44% 

```

My ISP (Verizon) returns some HTML for nonexistent Maven artifacts. The exception "ZipException: error in opening zip file" didn't tell which artifact is the problem.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #2080

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java [hunk 1]
```diff
@@ -92,10 +92,14 @@ static ClassDumper create(List<ClassPathEntry> entries) throws IOException {
...
-        if (!map.containsKey(className)) {
-          map.put(className, entry);
+      try {
+        for (String className : entry.getFileNames()) {
+          if (!map.containsKey(className)) {
+            map.put(className, entry);
+          }
         }
+      } catch (IOException ex) {
+        throw new IOException("Failed to read content of " + entry.getJar(), ex);
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java:102]: Maybe this should happen inside ClassPathEntry instead

File: dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java [hunk 2]
```diff
@@ -419,4 +421,19 @@ public void testMethodCodeNull() throws IOException, InvalidVersionSpecification
...
+  @Test
+  public void testInvalidJarFile() throws Exception {
+    String pomFile = "libraries-bom-2.7.0.pom";
+    Path nonZipFile = TestHelper.absolutePathOfResource(pomFile);
+    Artifact nonZipArtifact = new DefaultArtifact("com.google.cloud:libraries-bom:2.7.0")
+        .setFile(nonZipFile.toFile());
+
+    try {
+      ClassDumper.create(ImmutableList.of(new ClassPathEntry(nonZipArtifact)));
+      Assert.fail("ClassDumper shoudl raise IOException for an invalid JAR file.");
```
[the remark this answers is not in the document]
Comment (suztomo) [reply dependencies/src/test/java/com/google/cloud/tools/opensource/classpath/ClassDumperTest.java]: Fixed.

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java (hunk 1 above)
Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/ClassDumper.java]: Nice idea. Updated.

**Review by elharo — APPROVED** [review]
