### PR TITLE
To fix dependency graph traversal order

### LINKED ISSUE #493: LinkageCheckerRule: reachable flag broken
There was a bug: dependencyResolutionResult.getDependencies() was not returning items in breadth-first order. This is affecting reachability flag in LinkageCheckerRule

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #493 .

This is a preparation for #490.

### CODE REVIEW

File: enforcer-rules/src/main/java/com/google/cloud/tools/opensource/enforcer/LinkageCheckerRule.java [hunk 1]
```diff
@@ -146,8 +149,12 @@ public void execute(@Nonnull EnforcerRuleHelper helper) throws EnforcerRuleExcep
           new DefaultDependencyResolutionRequest(mavenProject, session);
       DependencyResolutionResult dependencyResolutionResult =
           projectDependenciesResolver.resolve(dependencyResolutionRequest);
-      return dependencyResolutionResult.getDependencies().stream()
```
Comment (suztomo) [inline enforcer-rules/src/main/java/com/google/cloud/tools/opensource/enforcer/LinkageCheckerRule.java]: `dependencyResolutionResult.getDependencies()` does not return Maven's breadth-first traversal order.
