### PR TITLE
specify short option

### LINKED ISSUE #1838: The option 'send-analytics' contains an illegal character : '-'
https://github.com/googleapis/java-spanner/pull/452/checks?check_run_id=1456675000 ("view raw log" from the dropdown at the top-right)

```
2020-11-26T01:46:55.5767983Z + java -jar linkage-monitor-latest-all-deps.jar com.google.cloud:libraries-bom
2020-11-26T01:46:55.6234944Z ##[error]Exception in thread "main" java.lang.IllegalArgumentException: The option 'send-analytics' contains an illegal character : '-'
2020-11-26T01:46:55.6247558Z 	at org.apache.commons.cli.OptionValidator.validateOption(OptionValidator.java:71)
2020-11-26T01:46:55.6248848Z 	at org.apache.commons.cli.Option.<init>(Option.java:146)
2020-11-26T01:46:55.6249816Z 	at org.apache.commons.cli.Options.addOption(Options.java:150)
2020-11-26T01:46:55.6250893Z 	at org.apache.commons.cli.Options.addOption(Options.java:131)
2020-11-26T01:46:55.6253365Z 	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.parseCommandLine(LinkageMonitor.java:124)
2020-11-26T01:46:55.6256397Z 	at com.google.cloud.tools.dependencies.linkagemonitor.LinkageMonitor.main(LinkageMonitor.java:96)
```

### PR DESCRIPTION
**Pull request by elharo**
@suztomo fixes #1838

### CODE REVIEW

File: linkage-monitor/src/test/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitorTest.java [hunk 1]
```diff
@@ -104,6 +104,12 @@ public void setup() throws IOException {
                 "(Lcom/google/protobuf/Message;)Lio/grpc/MethodDescriptor$Marshaller;",
                 false));
   }
+  
+  @Test
+  public void testCommandLine() {
+    String[] arguments = {"something"};
+    LinkageMonitor.parseCommandLine(arguments);
```
Comment (suztomo) [inline linkage-monitor/src/test/java/com/google/cloud/tools/dependencies/linkagemonitor/LinkageMonitorTest.java:111]: How about checking the return value to ensure the code below (at line 96 of LinkageMonitor.java) works fine?

```
    CommandLine commandLine = parseCommandLine(arguments);
    String bomCoordinates = commandLine.getArgList().get(0);
```

Linkage Monitor is invoked with the versionless coordinates. ([doc](https://github.com/GoogleCloudPlatform/cloud-opensource-java/tree/master/linkage-monitor#installation))

```
java -jar linkage-monitor-X.Y.Z-all-deps.jar com.google.cloud:libraries-bom
```

**Review by suztomo — APPROVED** [review]
Thank you for taking care of this.
