### PR TITLE
Special-case Mockito's MockMethodDispatcher

### LINKED ISSUE #407: ClasspathChecker cannot find mockito 2's MockMethodDispatcher
While investigating #394, newer mockito also fails the check. Classpath Checker shows following errors for `-a org.mockito:mockito-core:2.23.4,junit:junit:4.12`

```
mockito-core-2.23.4.jar (18 errors):
  ClassSymbolReference{sourceClassName=org.mockito.internal.creation.bytebuddy.MockMethodAdvice$ForReadObject, targetClassName=org.mockito.internal.creation.bytebuddy.MockMethodDispatcher, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ClassSymbolReference{sourceClassName=org.mockito.internal.creation.bytebuddy.MockMethodAdvice$ForEquals, targetClassName=org.mockito.internal.creation.bytebuddy.MockMethodDispatcher, subclass=false}, reason: CLASS_NOT_FOUND, target class location not found
  ...

```

The class `MockMethodDispatcher` is included in mockito code ([github url](https://github.com/mockito/mockito/blob/30d3127ee2c4e41452787a058a31b7a553ba3b00/src/main/java/org/mockito/internal/creation/bytebuddy/MockMethodDispatcher.java)). However, the jar file contains ".raw" file:

```
~/cloud-opensource-java$ jar tf `find ~/.m2 -name 'mockito-core-2.23.4.jar'` |grep MockMethodDispatcher
org/mockito/internal/creation/bytebuddy/MockMethodDispatcher.raw

```

# Investigation

```
/tmp/mockito-2.23.4$ file ./org/mockito/internal/creation/bytebuddy/MockMethodDispatcher.raw
./org/mockito/internal/creation/bytebuddy/MockMethodDispatcher.raw: compiled Java class data, version 50.0 (Java 1.6)
```

The ".raw" file is just a class file renamed to avoid the class loaded by different class loaders than the one in Mockito's. https://github.com/mockito/mockito/pull/847 . Mockito's class loader handles ".raw" files in special manner.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #407 .

### CODE REVIEW

File: dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java [hunk 1]
```diff
@@ -187,6 +187,16 @@ private static boolean problemFilter(Map.Entry<SymbolProblem, ClassFile> entry)
       return false;
     }
 
+    // Mockito's MockMethodDispatcher uses special class loader to load MockMethodDispatcher.raw
+    // https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/407
+    if (symbolProblem
```
Comment (elharo) [inline dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: you can compress this onto fewer lines

Comment (suztomo) [reply dependencies/src/main/java/com/google/cloud/tools/opensource/classpath/LinkageChecker.java]: Made it as a variable.
